package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Cirugia generated by hbm2java
 */
@Entity
@Table(name = "cirugia_procesar", schema = "public")
public class CirugiaProcesar extends Historial implements java.io.Serializable {
	
	private String txtComentario;
	private String txtDiagnostico;
	private Date FechaOperacion;

	public CirugiaProcesar() {
		super.setTipoServicio(new TipoServicio("CIR"));
	}

	public CirugiaProcesar(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("CIR"));
	}
	
	@Column(name = "comentario", nullable = false)
	public String getTxtComentario() {
		return txtComentario;
	}

	public void setTxtComentario(String txtComentario) {
		this.txtComentario = txtComentario;
	}

	@Column(name = "diagnostico", nullable = false)
	public String getTxtDiagnostico() {
		return txtDiagnostico;
	}

	public void setTxtDiagnostico(String txtDiagnostico) {
		this.txtDiagnostico = txtDiagnostico;
	}

	@Column(name = "fecha_operacion", nullable = false)
	@Temporal(TemporalType.DATE)
	public Date getFechaOperacion() {
		return FechaOperacion;
	}

	public void setFechaOperacion(Date fechaOperacion) {
		FechaOperacion = fechaOperacion;
	}

	@Override
	public String toString() {
		return "Modelo Cirugia,  id: " + super.getId();
	}

}
