package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cirugia generated by hbm2java
 */
@Entity
@Table(name = "cirugia_transquirurgica", schema = "public")
public class CirugiaTransquirurgico extends Historial implements java.io.Serializable {
	
	private String comentarios;
	private String otroInstrumental;
	private boolean instrumentalOftalmologia;
	private boolean instrumentalTraumatologia;
	private boolean instrumentalGeneral;
	private int otro;
	private String otroCalibre;
	private String otroMaterial;
	private int PDS;
	private String PDSCalibre;
	private int monocryl;
	private String monocrylCalibre;
	private int prolene;
	private String proleneCalibre;
	private int nylon;
	private String nylonCalibre;
	private int safil;
	private String safilCalibre;
	private int vicryl;
	private String vicrylCalibre;
	private String tecnica;

	public CirugiaTransquirurgico() {
		super.setTipoServicio(new TipoServicio("TRQ"));
	}

	public CirugiaTransquirurgico(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("TRQ"));
	}
	
	@Column(name = "comentario", nullable = false)
	public String getComentarios() {
		return comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "otro_instrumental", nullable = false)
	public String getOtroInstrumental() {
		return otroInstrumental;
	}

	public void setOtroInstrumental(String otroInstrumental) {
		this.otroInstrumental = otroInstrumental;
	}

	@Column(name = "instrumental_oftalmologia", nullable = false)
	public boolean isInstrumentalOftalmologia() {
		return instrumentalOftalmologia;
	}

	public void setInstrumentalOftalmologia(boolean instrumentalOftalmologia) {
		this.instrumentalOftalmologia = instrumentalOftalmologia;
	}

	@Column(name = "instrumental_traumatologia", nullable = false)
	public boolean isInstrumentalTraumatologia() {
		return instrumentalTraumatologia;
	}

	public void setInstrumentalTraumatologia(boolean instrumentalTraumatologia) {
		this.instrumentalTraumatologia = instrumentalTraumatologia;
	}

	@Column(name = "instrumental_general", nullable = false)
	public boolean isInstrumentalGeneral() {
		return instrumentalGeneral;
	}

	public void setInstrumentalGeneral(boolean instrumentalGeneral) {
		this.instrumentalGeneral = instrumentalGeneral;
	}

	@Column(name = "otro_cantidad", nullable = false)
	public int getOtro() {
		return otro;
	}

	public void setOtro(int otro) {
		this.otro = otro;
	}

	@Column(name = "otro_calibre", nullable = false)
	public String getOtroCalibre() {
		return otroCalibre;
	}

	public void setOtroCalibre(String otroCalibre) {
		this.otroCalibre = otroCalibre;
	}

	@Column(name = "otro_material", nullable = false)
	public String getOtroMaterial() {
		return otroMaterial;
	}

	public void setOtroMaterial(String otroMaterial) {
		this.otroMaterial = otroMaterial;
	}

	@Column(name = "pds_cantidad", nullable = false)
	public int getPDS() {
		return PDS;
	}

	public void setPDS(int pDS) {
		PDS = pDS;
	}

	@Column(name = "pds_calibre", nullable = false)
	public String getPDSCalibre() {
		return PDSCalibre;
	}

	public void setPDSCalibre(String pDSCalibre) {
		PDSCalibre = pDSCalibre;
	}

	@Column(name = "monocryl_cantidad", nullable = false)
	public int getMonocryl() {
		return monocryl;
	}

	public void setMonocryl(int monocryl) {
		this.monocryl = monocryl;
	}

	@Column(name = "monocryl_calibre", nullable = false)
	public String getMonocrylCalibre() {
		return monocrylCalibre;
	}

	public void setMonocrylCalibre(String monocrylCalibre) {
		this.monocrylCalibre = monocrylCalibre;
	}

	@Column(name = "prolene_cantidad", nullable = false)
	public int getProlene() {
		return prolene;
	}

	public void setProlene(int prolene) {
		this.prolene = prolene;
	}

	@Column(name = "prolene_calibre", nullable = false)
	public String getProleneCalibre() {
		return proleneCalibre;
	}

	public void setProleneCalibre(String proleneCalibre) {
		this.proleneCalibre = proleneCalibre;
	}

	@Column(name = "nylon_cantidad", nullable = false)
	public int getNylon() {
		return nylon;
	}

	public void setNylon(int nylon) {
		this.nylon = nylon;
	}

	@Column(name = "nylon_calibre", nullable = false)
	public String getNylonCalibre() {
		return nylonCalibre;
	}

	public void setNylonCalibre(String nylonCalibre) {
		this.nylonCalibre = nylonCalibre;
	}

	@Column(name = "safil_cantidad", nullable = false)
	public int getSafil() {
		return safil;
	}

	public void setSafil(int safil) {
		this.safil = safil;
	}

	@Column(name = "safil_calibre", nullable = false)
	public String getSafilCalibre() {
		return safilCalibre;
	}

	public void setSafilCalibre(String safilCalibre) {
		this.safilCalibre = safilCalibre;
	}

	@Column(name = "vicryl_cantidad", nullable = false)
	public int getVicryl() {
		return vicryl;
	}

	public void setVicryl(int vicryl) {
		this.vicryl = vicryl;
	}

	@Column(name = "vicryl_calibre", nullable = false)
	public String getVicrylCalibre() {
		return vicrylCalibre;
	}

	public void setVicrylCalibre(String vicrylCalibre) {
		this.vicrylCalibre = vicrylCalibre;
	}

	@Column(name = "tecnica", nullable = false)
	public String getTecnica() {
		return tecnica;
	}

	public void setTecnica(String tecnica) {
		this.tecnica = tecnica;
	}

	@Override
	public String toString() {
		return "Modelo Cirugia,  id: " + super.getId();
	}

}
