package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.zkoss.zul.Datebox;
import org.zkoss.zul.Textbox;
import org.zkoss.zul.Timebox;

/**
 * Cirugia generated by hbm2java
 */
@Entity
@Table(name = "cirugia_post_operatoria", schema = "public")
public class CirugiaPostOperatoria extends Historial implements java.io.Serializable {

	private String comentarios;
	private String otros;
	private String dosis4;
	private String analgesico2;
	private String dosis3;
	private String analgesico1;
	private String dosis2;
	private String antibiotico2;
	private String dosis1;
	private String antibiotico1;
	private Date horaRecuperacion;	
	
	public CirugiaPostOperatoria() {
		super.setTipoServicio(new TipoServicio("PTO"));
	}

	public CirugiaPostOperatoria(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("PTO"));
	}

	
	@Column(name = "comentarios")
	public String getComentarios() {
		return comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "otros")
	public String getOtros() {
		return otros;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	@Column(name = "dosis_analgesico2")
	public String getDosis4() {
		return dosis4;
	}

	public void setDosis4(String dosis4) {
		this.dosis4 = dosis4;
	}

	@Column(name = "analgesico2")
	public String getAnalgesico2() {
		return analgesico2;
	}

	public void setAnalgesico2(String analgesico2) {
		this.analgesico2 = analgesico2;
	}

	@Column(name = "dosis_analgesico1")
	public String getDosis3() {
		return dosis3;
	}

	public void setDosis3(String dosis3) {
		this.dosis3 = dosis3;
	}

	@Column(name = "analgesico1")
	public String getAnalgesico1() {
		return analgesico1;
	}

	public void setAnalgesico1(String analgesico1) {
		this.analgesico1 = analgesico1;
	}

	@Column(name = "dosis_antibiotico2")
	public String getDosis2() {
		return dosis2;
	}

	public void setDosis2(String dosis2) {
		this.dosis2 = dosis2;
	}

	@Column(name = "antibiotico2")
	public String getAntibiotico2() {
		return antibiotico2;
	}

	public void setAntibiotico2(String antibiotico2) {
		this.antibiotico2 = antibiotico2;
	}

	@Column(name = "dosis_antibiotico1")
	public String getDosis1() {
		return dosis1;
	}

	public void setDosis1(String dosis1) {
		this.dosis1 = dosis1;
	}

	@Column(name = "antibiotico1")
	public String getAntibiotico1() {
		return antibiotico1;
	}

	public void setAntibiotico1(String antibiotico1) {
		this.antibiotico1 = antibiotico1;
	}

	@Column(name = "horaRecuperacion")
	@Temporal(TemporalType.TIME)
	public Date getHoraRecuperacion() {
		return horaRecuperacion;
	}

	public void setHoraRecuperacion(Date horaRecuperacion) {
		this.horaRecuperacion = horaRecuperacion;
	}

	@Override
	public String toString() {
		return "Modelo Cirugia,  id: " + super.getId();
	}

}
