package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cirugia generated by hbm2java
 */
@Entity
@Table(name = "cirugia_pre_operatoria", schema = "public")
public class CirugiaPreOperatoria extends Historial implements java.io.Serializable {
	
	private String comentario;
	private int agujaEspinal;
	private int sondaEndotraqueal;
	private String lidocaina;
	private String oxigeno;
	private String isofrurano;
	private String zoletil;
	private String ketamina;
	private String propofol;
	private String dosis4;
	private String analgesico2;
	private String dosis3;
	private String analgesico1;
	private String dosis2;
	private String antibiotico2;
	private String dosis1;
	private String antibiotico1;
	private String atropina;
	private String midozolam;
	private String diacepam;
	private String acepromicina;
	

	public CirugiaPreOperatoria() {
		super.setTipoServicio(new TipoServicio("PRO"));
	}

	public CirugiaPreOperatoria(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("PRO"));
	}
	
	@Column(name = "comentario", nullable = false)
	public String getComentario() {
		return comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "aguja_espinal", nullable = true)
	public int getAgujaEspinal() {
		return agujaEspinal;
	}

	public void setAgujaEspinal(int agujaEspinal) {
		this.agujaEspinal = agujaEspinal;
	}

	@Column(name = "sonda_endotraqueal", nullable = true)
	public int getSondaEndotraqueal() {
		return sondaEndotraqueal;
	}

	
	public void setSondaEndotraqueal(int sondaEndotraqueal) {
		this.sondaEndotraqueal = sondaEndotraqueal;
	}

	@Column(name = "lidocaina", nullable = true)
	public String getLidocaina() {
		return lidocaina;
	}

	public void setLidocaina(String lidocaina) {
		this.lidocaina = lidocaina;
	}

	@Column(name = "oxigeno", nullable = true)
	public String getOxigeno() {
		return oxigeno;
	}

	public void setOxigeno(String oxigeno) {
		this.oxigeno = oxigeno;
	}

	@Column(name = "iso_frurano", nullable = true)
	public String getIsofrurano() {
		return isofrurano;
	}

	public void setIsofrurano(String isofrurano) {
		this.isofrurano = isofrurano;
	}

	@Column(name = "zoletil", nullable = true)
	public String getZoletil() {
		return zoletil;
	}

	public void setZoletil(String zoletil) {
		this.zoletil = zoletil;
	}

	@Column(name = "keratina", nullable = true)
	public String getKetamina() {
		return ketamina;
	}

	public void setKetamina(String ketamina) {
		this.ketamina = ketamina;
	}

	@Column(name = "propofol", nullable = true)
	public String getPropofol() {
		return propofol;
	}

	public void setPropofol(String propofol) {
		this.propofol = propofol;
	}

	@Column(name = "dosis_Analgesico2", nullable = true)
	public String getDosis4() {
		return dosis4;
	}

	public void setDosis4(String dosis4) {
		this.dosis4 = dosis4;
	}

	@Column(name = "analgesico2", nullable = true)
	public String getAnalgesico2() {
		return analgesico2;
	}

	public void setAnalgesico2(String analgesico2) {
		this.analgesico2 = analgesico2;
	}

	@Column(name = "dosis_Analgesico1", nullable = true)
	public String getDosis3() {
		return dosis3;
	}

	public void setDosis3(String dosis3) {
		this.dosis3 = dosis3;
	}

	@Column(name = "analgesico1", nullable = true)
	public String getAnalgesico1() {
		return analgesico1;
	}

	public void setAnalgesico1(String analgesico1) {
		this.analgesico1 = analgesico1;
	}

	@Column(name = "dosis_Antibiotico2", nullable = true)
	public String getDosis2() {
		return dosis2;
	}

	public void setDosis2(String dosis2) {
		this.dosis2 = dosis2;
	}

	@Column(name = "antibiotico2", nullable = true)
	public String getAntibiotico2() {
		return antibiotico2;
	}

	public void setAntibiotico2(String antibiotico2) {
		this.antibiotico2 = antibiotico2;
	}

	@Column(name = "dosis_Antibiotico1", nullable = true)
	public String getDosis1() {
		return dosis1;
	}

	public void setDosis1(String dosis1) {
		this.dosis1 = dosis1;
	}

	@Column(name = "antibiotico1", nullable = true)
	public String getAntibiotico1() {
		return antibiotico1;
	}

	public void setAntibiotico1(String antibiotico1) {
		this.antibiotico1 = antibiotico1;
	}

	@Column(name = "atropina", nullable = true)
	public String getAtropina() {
		return atropina;
	}

	public void setAtropina(String atropina) {
		this.atropina = atropina;
	}

	@Column(name = "midozolam", nullable = true)
	public String getMidozolam() {
		return midozolam;
	}

	public void setMidozolam(String midozolam) {
		this.midozolam = midozolam;
	}

	@Column(name = "diacepam", nullable = true)
	public String getDiacepam() {
		return diacepam;
	}

	public void setDiacepam(String diacepam) {
		this.diacepam = diacepam;
	}

	@Column(name = "acepromicina", nullable = true)
	public String getAcepromicina() {
		return acepromicina;
	}

	public void setAcepromicina(String acepromicina) {
		this.acepromicina = acepromicina;
	}

	@Override
	public String toString() {
		return "Modelo Cirugia,  id: " + super.getId();
	}

}
