package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Consistencia generated by hbm2java
 */
@Entity
@Table(name = "consistencia", schema = "public")
public class Consistencia implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';
	private Set<Dermatologia> dermatologias = new HashSet<Dermatologia>(0);

	public Consistencia() {
	}

	public Consistencia(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_CONSISTENCIA", sequenceName = "seq_consistencia", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_CONSISTENCIA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consistencia")
//	public Set<Paciente> getPacientes() {
//		return this.pacientes;
//	}
//
//	public void setPacientes(Set<Paciente> pacientes) {
//		this.pacientes = pacientes;
//	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dermatologia_consistencia", schema = "public", joinColumns = { @JoinColumn(name = "consistenciaid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dermatologia_consid", nullable = false, updatable = false) })
	public Set<Dermatologia> getDermatologias() {
		return dermatologias;
	}

	public void setDermatologias(Set<Dermatologia> dermatologias) {
		this.dermatologias = dermatologias;
	}
	
	@Override
	public boolean equals(Object obj) {
		Consistencia comparacion = (Consistencia) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Consistencia, id: " + id;
	}

}
