package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsultaGeneral generated by hbm2java
 */
@Entity
@Table(name = "consulta_general", schema = "public")
public class ConsultaGeneral extends Historial implements java.io.Serializable {
	
	private String observaciones;
	private String tratamientoEnviado;
	private String tratamientoAplicado;
	private String tratamientoIndicaciones;
	private String patologiaComentario;
	private String diagnosticoDefinitivo;
	private String diagnosticoDiferencial;
	private String diagnosticoTentativo;
	private String diagnosticoProcedimiento;
	private String servicioDescripcion;
	private String caracter;
	private String prepucio;
	private String testiculos;
	private String secrecionVaginal;
	private String vejiga;
	private String orina;
	private String tacto;
	private String olfato;
	private String gusto;
	private String oido;
	private String vista;
	private String libido;
	private String contactoAnimal;
	private String pelajeEstado;
	private String rinnon;
	private String higado;
	private String bazo;
	private String motivoIngreso;
	private boolean mucosa;
	private boolean ectoparasitos;
	private boolean ruidoAdventicios;
	private boolean apetito;
	private int pulsoYugular;
	private int pulsoArterial;
	private int pulso;
	private int frecuenciaCardiaca;
	private int respiracion;
	private int tpc;
	private int temperatura;
	private int partos;
	private int altura;
	private int peso;
	private Date inicioEnfermedad;
	private Date castracion;
	private Date ultimoCelo;
	private Date ultimoAlimento;
	private TipoAlimentacion tipoAlimentacion;
	private Frecuencia frecuenciaAlimento;
	private Set<Ganglio> ganglios = new HashSet<Ganglio>(0);

	
	public ConsultaGeneral() {
		super.setTipoServicio(new TipoServicio("CGL"));
	}

	/*
	 * Lo hago luego 
	 */
	public ConsultaGeneral(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setPaciente(paciente);		
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("CGL"));
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "tratamiento_enviado", nullable = false)
	public String getTratamientoEnviado() {
		return this.tratamientoEnviado;
	}

	public void setTratamientoEnviado(String tratamientoEnviado) {
		this.tratamientoEnviado = tratamientoEnviado;
	}

	@Column(name = "tratamiento_aplicado")
	public String getTratamientoAplicado() {
		return this.tratamientoAplicado;
	}

	public void setTratamientoAplicado(String tratamientoAplicado) {
		this.tratamientoAplicado = tratamientoAplicado;
	}

	@Column(name = "tratamiento_indicaciones")
	public String getTratamientoIndicaciones() {
		return this.tratamientoIndicaciones;
	}

	public void setTratamientoIndicaciones(String tratamientoIndicaciones) {
		this.tratamientoIndicaciones = tratamientoIndicaciones;
	}

	@Column(name = "patologia_comentario")
	public String getPatologiaComentario() {
		return this.patologiaComentario;
	}

	public void setPatologiaComentario(String patologiaComentario) {
		this.patologiaComentario = patologiaComentario;
	}

	@Column(name = "diagnostico_definitivo", nullable = false)
	public String getDiagnosticoDefinitivo() {
		return this.diagnosticoDefinitivo;
	}

	public void setDiagnosticoDefinitivo(String diagnosticoDefinitivo) {
		this.diagnosticoDefinitivo = diagnosticoDefinitivo;
	}

	@Column(name = "diagnostico_diferencial")
	public String getDiagnosticoDiferencial() {
		return this.diagnosticoDiferencial;
	}

	public void setDiagnosticoDiferencial(String diagnosticoDiferencial) {
		this.diagnosticoDiferencial = diagnosticoDiferencial;
	}

	@Column(name = "diagnostico_tentativo")
	public String getDiagnosticoTentativo() {
		return this.diagnosticoTentativo;
	}

	public void setDiagnosticoTentativo(String diagnosticoTentativo) {
		this.diagnosticoTentativo = diagnosticoTentativo;
	}

	@Column(name = "diagnostico_procedimiento")
	public String getDiagnosticoProcedimiento() {
		return this.diagnosticoProcedimiento;
	}

	public void setDiagnosticoProcedimiento(String diagnosticoProcedimiento) {
		this.diagnosticoProcedimiento = diagnosticoProcedimiento;
	}	

	@Column(name = "servicio_descripcion")
	public String getServicioDescripcion() {
		return servicioDescripcion;
	}

	public void setServicioDescripcion(String servicioDescripcion) {
		this.servicioDescripcion = servicioDescripcion;
	}

	@Column(name = "caracter", nullable = false)
	public String getCaracter() {
		return caracter;
	}

	public void setCaracter(String caracter) {
		this.caracter = caracter;
	}

	@Column(name = "prepucio")
	public String getPrepucio() {
		return this.prepucio;
	}

	public void setPrepucio(String prepucio) {
		this.prepucio = prepucio;
	}

	@Column(name = "testiculos")
	public String getTesticulos() {
		return this.testiculos;
	}

	public void setTesticulos(String testiculos) {
		this.testiculos = testiculos;
	}

	@Column(name = "secrecion_vaginal")
	public String getSecrecionVaginal() {
		return this.secrecionVaginal;
	}

	public void setSecrecionVaginal(String secrecionVaginal) {
		this.secrecionVaginal = secrecionVaginal;
	}

	@Column(name = "vejiga")
	public String getVejiga() {
		return this.vejiga;
	}

	public void setVejiga(String vejiga) {
		this.vejiga = vejiga;
	}

	@Column(name = "orina")
	public String getOrina() {
		return this.orina;
	}

	public void setOrina(String orina) {
		this.orina = orina;
	}

	@Column(name = "tacto", nullable = false)
	public String getTacto() {
		return this.tacto;
	}

	public void setTacto(String tacto) {
		this.tacto = tacto;
	}

	@Column(name = "olfato", nullable = false)
	public String getOlfato() {
		return this.olfato;
	}

	public void setOlfato(String olfato) {
		this.olfato = olfato;
	}

	@Column(name = "gusto", nullable = false)
	public String getGusto() {
		return this.gusto;
	}

	public void setGusto(String gusto) {
		this.gusto = gusto;
	}

	@Column(name = "oido", nullable = false)
	public String getOido() {
		return this.oido;
	}

	public void setOido(String oido) {
		this.oido = oido;
	}

	@Column(name = "vista", nullable = false)
	public String getVista() {
		return this.vista;
	}

	public void setVista(String vista) {
		this.vista = vista;
	}

	@Column(name = "libido")
	public String getLibido() {
		return this.libido;
	}

	public void setLibido(String libido) {
		this.libido = libido;
	}

	@Column(name = "contacto_animal", nullable = false)
	public String getContactoAnimal() {
		return this.contactoAnimal;
	}

	public void setContactoAnimal(String contactoAnimal) {
		this.contactoAnimal = contactoAnimal;
	}

	@Column(name = "pelaje_estado", nullable = false)
	public String getPelajeEstado() {
		return this.pelajeEstado;
	}

	public void setPelajeEstado(String pelajeEstado) {
		this.pelajeEstado = pelajeEstado;
	}

	@Column(name = "rinon")
	public String getRinnon() {
		return this.rinnon;
	}

	public void setRinnon(String rinnon) {
		this.rinnon = rinnon;
	}

	@Column(name = "higado")
	public String getHigado() {
		return this.higado;
	}

	public void setHigado(String higado) {
		this.higado = higado;
	}

	@Column(name = "bazo")
	public String getBazo() {
		return this.bazo;
	}

	public void setBazo(String bazo) {
		this.bazo = bazo;
	}

	@Column(name = "motivo_ingreso", nullable = false)
	public String getMotivoIngreso() {
		return this.motivoIngreso;
	}

	public void setMotivoIngreso(String motivoIngreso) {
		this.motivoIngreso = motivoIngreso;
	}

	@Column(name = "mucosa", nullable = false)
	public boolean getMucosa() {
		return this.mucosa;
	}

	public void setMucosa(boolean mucosa) {
		this.mucosa = mucosa;
	}

	@Column(name = "ectoparasitos", nullable = false)
	public boolean getEctoparasitos() {
		return this.ectoparasitos;
	}

	public void setEctoparasitos(boolean ectoparasitos) {
		this.ectoparasitos = ectoparasitos;
	}

	@Column(name = "ruido_adventicios", nullable = false)
	public boolean getRuidoAdventicios() {
		return this.ruidoAdventicios;
	}

	public void setRuidoAdventicios(boolean ruidoAdventicios) {
		this.ruidoAdventicios = ruidoAdventicios;
	}

	@Column(name = "apetito", nullable = false)
	public boolean getApetito() {
		return this.apetito;
	}

	public void setApetito(boolean apetito) {
		this.apetito = apetito;
	}

	@Column(name = "pulso_yugular", nullable = false)
	public int getPulsoYugular() {
		return this.pulsoYugular;
	}

	public void setPulsoYugular(int pulsoYugular) {
		this.pulsoYugular = pulsoYugular;
	}

	@Column(name = "pulso_arterial", nullable = false)
	public int getPulsoArterial() {
		return this.pulsoArterial;
	}

	public void setPulsoArterial(int pulsoArterial) {
		this.pulsoArterial = pulsoArterial;
	}

	@Column(name = "pulso", nullable = false)
	public int getPulso() {
		return this.pulso;
	}

	public void setPulso(int pulso) {
		this.pulso = pulso;
	}

	@Column(name = "frecuencia_cardiaca", nullable = false)
	public int getFrecuenciaCardiaca() {
		return this.frecuenciaCardiaca;
	}

	public void setFrecuenciaCardiaca(int frecuenciaCardiaca) {
		this.frecuenciaCardiaca = frecuenciaCardiaca;
	}

	@Column(name = "respiracion", nullable = false)
	public int getRespiracion() {
		return this.respiracion;
	}

	public void setRespiracion(int respiracion) {
		this.respiracion = respiracion;
	}

	@Column(name = "tpc", nullable = false)
	public int getTpc() {
		return this.tpc;
	}

	public void setTpc(int tpc) {
		this.tpc = tpc;
	}

	@Column(name = "temperatura", nullable = false)
	public int getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(int temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "partos")
	public int getPartos() {
		return this.partos;
	}

	public void setPartos(int partos) {
		this.partos = partos;
	}

	@Column(name = "altura", nullable = false)
	public int getAltura() {
		return this.altura;
	}

	public void setAltura(int altura) {
		this.altura = altura;
	}

	@Column(name = "peso", nullable = false)
	public int getPeso() {
		return this.peso;
	}

	public void setPeso(int peso) {
		this.peso = peso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicio_enfermedad", nullable = false, length = 13)
	public Date getInicioEnfermedad() {
		return this.inicioEnfermedad;
	}

	public void setInicioEnfermedad(Date inicioEnfermedad) {
		this.inicioEnfermedad = inicioEnfermedad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "castracion", length = 13)
	public Date getCastracion() {
		return this.castracion;
	}

	public void setCastracion(Date castracion) {
		this.castracion = castracion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimo_celo", length = 13)
	public Date getUltimoCelo() {
		return this.ultimoCelo;
	}

	public void setUltimoCelo(Date ultimoCelo) {
		this.ultimoCelo = ultimoCelo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimo_alimento", nullable = false, length = 13)
	public Date getUltimoAlimento() {
		return this.ultimoAlimento;
	}

	public void setUltimoAlimento(Date ultimoAlimento) {
		this.ultimoAlimento = ultimoAlimento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idtipo_alimentacion", nullable = false)
	public TipoAlimentacion getTipoAlimentacion() {
		return this.tipoAlimentacion;
	}

	public void setTipoAlimentacion(TipoAlimentacion tipoAlimentacion) {
		this.tipoAlimentacion = tipoAlimentacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idfrecuencia_alimento", nullable = false)
	public Frecuencia getFrecuenciaAlimento() {
		return this.frecuenciaAlimento;
	}

	public void setFrecuenciaAlimento(Frecuencia frecuenciaAlimento) {
		this.frecuenciaAlimento = frecuenciaAlimento;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "consultageneral_ganglio", schema = "public", joinColumns = { @JoinColumn(name = "consultageneralid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ganglioid", nullable = false, updatable = false) })
	public Set<Ganglio> getGanglios() {
		return this.ganglios;
	}

	public void setGanglios(Set<Ganglio> ganglios) {
		this.ganglios = ganglios;
	}

	@Override
	public String toString() {
		return "Modelo ConsultaGeneral, id: " + super.getId();
	}

}
