package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * EntidadExterna generated by hbm2java
 */
@Entity
@Table(name = "entidad_externa", schema = "public")
public class EntidadExterna implements java.io.Serializable {

	private int id;
	private Imagen imagen;
	private Ciudad ciudad;
	private TipoEntidadExterna tipoEntidadExterna;
	private String nombre;
	private String descripcion;
	private String direccion;
	private String telefono;
	private String fax;
	private String web;
	private String correo;
	private String rif;
	private String nit;
	private char estatus = 'A';

	public EntidadExterna() {
	}

	public EntidadExterna(int id, Ciudad ciudad,
			TipoEntidadExterna tipoEntidadExterna, String nombre, char estatus) {
		this.id = id;
		this.ciudad = ciudad;
		this.tipoEntidadExterna = tipoEntidadExterna;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public EntidadExterna(int id, Imagen imagen, Ciudad ciudad,
			TipoEntidadExterna tipoEntidadExterna, String nombre,
			String descripcion, String direccion, String telefono, String fax,
			String web, String correo, String rif, String nit, char estatus) {
		this.id = id;
		this.imagen = imagen;
		this.ciudad = ciudad;
		this.tipoEntidadExterna = tipoEntidadExterna;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.telefono = telefono;
		this.fax = fax;
		this.web = web;
		this.correo = correo;
		this.rif = rif;
		this.nit = nit;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_ENTIDAD_EXTERNA", sequenceName = "seq_entidad_externa", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_ENTIDAD_EXTERNA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "imagenid")
	public Imagen getImagen() {
		return this.imagen;
	}

	public void setImagen(Imagen imagen) {
		this.imagen = imagen;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ciudadid", nullable = false)
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_entidad_externaid", nullable = false)
	public TipoEntidadExterna getTipoEntidadExterna() {
		return this.tipoEntidadExterna;
	}

	public void setTipoEntidadExterna(TipoEntidadExterna tipoEntidadExterna) {
		this.tipoEntidadExterna = tipoEntidadExterna;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "fax", length = 12)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "web")
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	@Column(name = "correo")
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "rif", length = 20)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "nit", length = 20)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Override
	public boolean equals(Object obj) {
		EntidadExterna comparacion = (EntidadExterna) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo EntidadExterna, id: " + id;
	}

}
