package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "public")
public class Estado implements java.io.Serializable {

	private int id;
	private String nombre;
	private String abreviatura;
	private char estatus = 'A';
	private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

	public Estado() {
	}

	public Estado(int id, String abreviatura, char estatus) {
		this.id = id;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
	}

	public Estado(int id, String nombre, String abreviatura, char estatus,
			Set<Ciudad> ciudads) {
		this.id = id;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
		this.estatus = estatus;
		this.ciudads = ciudads;
	}

	@Id
	@SequenceGenerator(name = "SEQ_ESTADO", sequenceName = "seq_estado", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_ESTADO")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviatura", nullable = false, length = 5)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Ciudad> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<Ciudad> ciudads) {
		this.ciudads = ciudads;
	}

	@Override
	public boolean equals(Object obj) {
		Estado comparacion = (Estado) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Estado, id: " + id;
	}

}
