package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * GeneroPublicacion generated by hbm2java
 */
@Entity
@Table(name = "genero_publicacion", schema = "public")
public class GeneroPublicacion implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private char estatus = 'A';
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public GeneroPublicacion() {
	}

	public GeneroPublicacion(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public GeneroPublicacion(int id, String nombre, String descripcion,
			char estatus, Set<Publicacion> publicacions) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.publicacions = publicacions;
	}

	@Id
	@SequenceGenerator(name = "SEQ_GENERO_PUBLICACION", sequenceName = "seq_genero_publicacion", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_GENERO_PUBLICACION")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", columnDefinition = "text")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "generoPublicacion")
	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

	@Override
	public boolean equals(Object obj) {
		GeneroPublicacion comparacion = (GeneroPublicacion) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo GeneroPublicacion, id: " + id;
	}

}
