package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * LesionPS generated by hbm2java
 */
@Entity
@Table(name = "lesion_PS", schema = "public")
public class LesionPS implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';
	private Set<Dermatologia> dermatologias = new HashSet<Dermatologia>(0);
	
	public LesionPS() {
	}

	public LesionPS(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_LESIONPS", sequenceName = "seq_lesionPS", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_LESIONPS")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dermatologia_lesionps", schema = "public", joinColumns = { @JoinColumn(name = "lesionpsid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dermatologiaid", nullable = false, updatable = false) })
	public Set<Dermatologia> getDermatologias() {
		return dermatologias;
	}

	public void setDermatologias(Set<Dermatologia> dermatologias) {
		this.dermatologias = dermatologias;
	}

	@Override
	public boolean equals(Object obj) {
		LesionPS comparacion = (LesionPS) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo LesionPS, id: " + id;
	}

}
