package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Neurologia generated by hbm2java
 */
@Entity
@Table(name = "neurologia", schema = "public")
public class Neurologia extends Historial implements java.io.Serializable {
	
	private CursoClinico cursoClinico;
	private ValoracionSubjetiva valoracionSubjetiva;
	private Postura postura;
	private String otras;
	
	private Ataxia ataxia;
	private ParesiaPlejia paresiaPlejia;
	private Dolor dolor;
	private ParesiaPlejia paresiaPlejia1;
	private Dolor dolor1;
	private Cojera cojera;
	
	private ReaccionPostular reaccionPostular;
	private ReaccionPostular reaccionPostular1;
	private ReaccionPostular reaccionPostular2;
	private ReaccionPostular reaccionPostular3;
	private ReaccionPostular reaccionPostular4;
	private ReaccionPostular reaccionPostular5;
	private ReaccionPostular reaccionPostular6;
	private ReaccionPostular reaccionPostular7;
	private ReaccionPostular reaccionPostular8;
	private ReaccionPostular reaccionPostular9;
	private ReaccionPostular reaccionPostular10;
	private ReaccionPostular reaccionPostular11;
	private ReaccionPostular reaccionPostular12;
	private ReaccionPostular reaccionPostular13;
	private ReaccionPostular reaccionPostular14;
	private ReaccionPostular reaccionPostular15;
	private ReaccionPostular reaccionPostular16;
	private ReaccionPostular reaccionPostular17;
	private ReaccionPostular reaccionPostular18;
	private ReaccionPostular reaccionPostular19;
	private ReaccionPostular reaccionPostular20;
	private ReaccionPostular reaccionPostular21;
	private ReaccionPostular reaccionPostular22;
	private ReaccionPostular reaccionPostular23;
	private ReaccionPostular reaccionPostular24;
	private ReaccionPostular reaccionPostular25;
	private ReaccionPostular reaccionPostular26;
	private ReaccionPostular reaccionPostular27;
	private ReaccionPostular reaccionPostular28;
	private ReaccionPostular reaccionPostular29;
	private ReaccionPostular reaccionPostular30;
	private ReaccionPostular reaccionPostular31;
	private ReaccionPostular reaccionPostular32;
	private ReaccionPostular reaccionPostular33;
	private ReaccionPostular reaccionPostular34;
	private ReaccionPostular reaccionPostular35;
	private ReaccionPostular reaccionPostular36;
	private ReaccionPostular reaccionPostular37;
	private ReaccionPostular reaccionPostular38;
	private ReaccionPostular reaccionPostular39;
	private ReaccionPostular reaccionPostular40;
	private ReaccionPostular reaccionPostular41;
	private ReaccionPostular reaccionPostular42;
	private ReaccionPostular reaccionPostular43;
	private ReaccionPostular reaccionPostular44;
	private ReaccionPostular reaccionPostular45;
	private ReaccionPostular reaccionPostular46;
	private ReaccionPostular reaccionPostular47;
	private ReaccionPostular reaccionPostular48;
	private ReaccionPostular reaccionPostular49;
	private ReaccionPostular reaccionPostular50;
	private ReaccionPostular reaccionPostular51;
	
	private ReflejoEspinal reflejoEspinal;
	private ReflejoEspinal reflejoEspinal1;
	private ReflejoEspinal reflejoEspinal2;
	private ReflejoEspinal reflejoEspinal3;
	private ReflejoEspinal reflejoEspinal4;
	private ReflejoEspinal reflejoEspinal5;
	private ReflejoEspinal reflejoEspinal6;
	private ReflejoEspinal reflejoEspinal7;
	private ReflejoEspinal reflejoEspinal8;
	private ReflejoEspinal reflejoEspinal9;
	private ReflejoEspinal reflejoEspinal10;
	private ReflejoEspinal reflejoEspinal11;
	private ReflejoEspinal reflejoEspinal12;
	private ReflejoEspinal reflejoEspinal13;
	private ReflejoEspinal reflejoEspinal14;
	private ReflejoEspinal reflejoEspinal15;
	private ReflejoEspinal reflejoEspinal16;
	private ReflejoEspinal reflejoEspinal17;
	
	private Dolor dolor2;
	private Dolor dolor3;
	
	private Boolean cervical;
	private Boolean toracica;
	private Boolean toracolumbar;
	private Boolean lumbar;
	private Boolean lumbosacra;
	private Boolean caudal;
	private Boolean ninguna;
	private Boolean otra;
	
	private String cutaneaTroncoNormal;
	
	private String diagnosticoProcedimiento;
	private String diagnosticoTentativo;
	private String diagnosticoDiferencial;
	private String diagnosticoDefinitivo;
	private String patologiaComentario;
	private String tratamientoIndicaciones;
	private String tratamientoAplicado;
	private String tratamientoEnviado;
	private String observaciones;
	private char estatus = 'A';
	
	public Neurologia(Ataxia ataxia, Cojera cojera, CursoClinico cursoClinico, Dolor dolor,
			ParesiaPlejia paresiaPlejia, Postura postura, ReaccionPostular reaccionPostular,
			ReflejoEspinal reflejoEspinal, ValoracionSubjetiva valoracionSubjetiva, String diagnosticoProcedimiento,
			String diagnosticoTentativo, String diagnosticoDiferencial, String diagnosticoDefinitivo,
			String patologiaComentario, String tratamientoIndicaciones, String tratamientoAplicado,
			String tratamientoEnviado, String observaciones, String otras, char estatus) {
		this.ataxia = ataxia;
		this.cojera = cojera;
		this.cursoClinico = cursoClinico;
		this.dolor= dolor;
		this.paresiaPlejia = paresiaPlejia;
		this.paresiaPlejia = paresiaPlejia1;
		this.postura = postura;
		this.reaccionPostular = reaccionPostular;
		this.reflejoEspinal = reflejoEspinal;
		this.valoracionSubjetiva = valoracionSubjetiva;
		this.diagnosticoProcedimiento = diagnosticoProcedimiento;
		this.diagnosticoTentativo = diagnosticoTentativo;
		this.diagnosticoDiferencial = diagnosticoDiferencial;
		this.diagnosticoDefinitivo = diagnosticoDefinitivo;
		this.patologiaComentario = patologiaComentario;
		this.tratamientoIndicaciones = tratamientoIndicaciones;
		this.tratamientoAplicado = tratamientoAplicado;
		this.tratamientoEnviado = tratamientoEnviado;
		this.observaciones = observaciones;
		this.otras = otras;
		this.estatus = estatus;
	}	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cursoclinicoid", nullable = false)
	public CursoClinico getCursoClinico() {
		return this.cursoClinico;
	}

	public void setCursoClinico(CursoClinico cursoClinico) {
		this.cursoClinico = cursoClinico;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "valoracionid", nullable = false)
	public ValoracionSubjetiva getValoracionSubjetiva() {
		return this.valoracionSubjetiva;
	}

	public void setValoracionSubjetiva(ValoracionSubjetiva valoracionSubjetiva) {
		this.valoracionSubjetiva = valoracionSubjetiva;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "posturaid", nullable = false)
	public Postura getPostura() {
		return this.postura;
	}

	public void setPostura(Postura postura) {
		this.postura = postura;
	}
	
	public String getOtras() {
		return otras;
	}

	public void setOtras(String otras) {
		this.otras = otras;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ataxiaid", nullable = false)
	public Ataxia getAtaxia() {
		return this.ataxia;
	}

	public void setAtaxia(Ataxia ataxia) {
		this.ataxia = ataxia;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "paresiaid", nullable = false)
	public ParesiaPlejia getParesiaPlejia() {
		return this.paresiaPlejia;
	}

	public void setParesiaPlejia(ParesiaPlejia paresiaPlejia) {
		this.paresiaPlejia = paresiaPlejia;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pasocortoid", nullable = false)
	public Dolor getDolor() {
		return this.dolor;
	}

	public void setDolor(Dolor dolor) {
		this.dolor = dolor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "plejiaid", nullable = false)
	public ParesiaPlejia getParesiaPlejia1() {
		return this.paresiaPlejia1;
	}

	public void setParesiaPlejia1(ParesiaPlejia paresiaPlejia1) {
		this.paresiaPlejia1 = paresiaPlejia1;
	}	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mantenersepieid", nullable = false)	
	public Dolor getDolor1() {
		return this.dolor1;
	}

	public void setDolor1(Dolor dolor1) {
		this.dolor1 = dolor1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cojeraid", nullable = false)
	public Cojera getCojera() {
		return this.cojera;
	}

	public void setCojera(Cojera cojera) {
		this.cojera = cojera;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "propiosecciontoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular() {
		return this.reaccionPostular;
	}

	public void setReaccionPostular(ReaccionPostular reaccionPostular) {
		this.reaccionPostular = reaccionPostular;
	}	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "propiosecciontoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular1() {
		return this.reaccionPostular1;
	}

	public void setReaccionPostular1(ReaccionPostular reaccionPostular1) {
		this.reaccionPostular1 = reaccionPostular1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "propioseccionpelvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular2() {
		return this.reaccionPostular2;
	}

	public void setReaccionPostular2(ReaccionPostular reaccionPostular2) {
		this.reaccionPostular2 = reaccionPostular2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "propioseccionpelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular3() {
		return this.reaccionPostular3;
	}

	public void setReaccionPostular3(ReaccionPostular reaccionPostular3) {
		this.reaccionPostular3 = reaccionPostular3;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "saltotoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular4() {
		return this.reaccionPostular4;
	}

	public void setReaccionPostular4(ReaccionPostular reaccionPostular4) {
		this.reaccionPostular4 = reaccionPostular4;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "saltotoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular5() {
		return this.reaccionPostular5;
	}

	public void setReaccionPostular5(ReaccionPostular reaccionPostular5) {
		this.reaccionPostular5 = reaccionPostular5;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "saltopelvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular6() {
		return this.reaccionPostular6;
	}

	public void setReaccionPostular6(ReaccionPostular reaccionPostular6) {
		this.reaccionPostular6 = reaccionPostular6;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "saltopelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular7() {
		return this.reaccionPostular7;
	}

	public void setReaccionPostular7(ReaccionPostular reaccionPostular7) {
		this.reaccionPostular7 = reaccionPostular7;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "carretillatoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular8() {
		return this.reaccionPostular8;
	}

	public void setReaccionPostular8(ReaccionPostular reaccionPostular8) {
		this.reaccionPostular8 = reaccionPostular8;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "carretillatoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular9() {
		return this.reaccionPostular9;
	}
	
	public void setReaccionPostular9(ReaccionPostular reaccionPostular9) {
		this.reaccionPostular9 = reaccionPostular9;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "carretillapalvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular10() {
		return this.reaccionPostular10;
	}

	public void setReaccionPostular10(ReaccionPostular reaccionPostular10) {
		this.reaccionPostular10 = reaccionPostular10;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "carretillapelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular11() {
		return this.reaccionPostular11;
	}

	public void setReaccionPostular11(ReaccionPostular reaccionPostular11) {
		this.reaccionPostular11 = reaccionPostular11;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hemiestacionmarchatoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular12() {
		return this.reaccionPostular12;
	}

	public void setReaccionPostular12(ReaccionPostular reaccionPostular12) {
		this.reaccionPostular12 = reaccionPostular12;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hemiestacionmarchatoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular13() {
		return this.reaccionPostular13;
	}

	public void setReaccionPostular13(ReaccionPostular reaccionPostular13) {
		this.reaccionPostular13 = reaccionPostular13;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hemiestacionmarchapelvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular14() {
		return this.reaccionPostular14;
	}

	public void setReaccionPostular14(ReaccionPostular reaccionPostular14) {
		this.reaccionPostular14 = reaccionPostular14;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hemiestacionmarchapelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular15() {
		return this.reaccionPostular15;
	}

	public void setReaccionPostular15(ReaccionPostular reaccionPostular15) {
		this.reaccionPostular15 = reaccionPostular15;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "colocacionmarchatoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular16() {
		return this.reaccionPostular16;
	}

	public void setReaccionPostular16(ReaccionPostular reaccionPostular16) {
		this.reaccionPostular16 = reaccionPostular16;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "colocacionmarchatoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular17() {
		return this.reaccionPostular17;
	}

	public void setReaccionPostular17(ReaccionPostular reaccionPostular17) {
		this.reaccionPostular17 = reaccionPostular17;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "colocacionmarchapelvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular18() {
		return this.reaccionPostular18;
	}

	public void setReaccionPostular18(ReaccionPostular reaccionPostular18) {
		this.reaccionPostular18 = reaccionPostular18;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "colocacionmarchapelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular19() {
		return this.reaccionPostular19;
	}

	public void setReaccionPostular19(ReaccionPostular reaccionPostular19) {
		this.reaccionPostular19 = reaccionPostular19;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorpostulartoracicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular20() {
		return this.reaccionPostular20;
	}

	public void setReaccionPostular20(ReaccionPostular reaccionPostular20) {
		this.reaccionPostular20 = reaccionPostular20;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorpostulartoracicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular21() {
		return this.reaccionPostular21;
	}

	public void setReaccionPostular21(ReaccionPostular reaccionPostular21) {
		this.reaccionPostular21 = reaccionPostular21;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorpostularpelvicaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular22() {
		return this.reaccionPostular22;
	}

	public void setReaccionPostular22(ReaccionPostular reaccionPostular22) {
		this.reaccionPostular22 = reaccionPostular22;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorpostularpelvicaderid", nullable = false)
	public ReaccionPostular getReaccionPostular23() {
		return this.reaccionPostular23;
	}

	public void setReaccionPostular23(ReaccionPostular reaccionPostular23) {
		this.reaccionPostular23 = reaccionPostular23;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "olfatoizqid", nullable = false)
	public ReaccionPostular getReaccionPostular24() {
		return this.reaccionPostular24;
	}

	public void setReaccionPostular24(ReaccionPostular reaccionPostular24) {
		this.reaccionPostular24 = reaccionPostular24;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "olfatoderid", nullable = false)
	public ReaccionPostular getReaccionPostular25() {
		return this.reaccionPostular25;
	}

	public void setReaccionPostular25(ReaccionPostular reaccionPostular25) {
		this.reaccionPostular25 = reaccionPostular25;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "respuestamenazaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular26() {
		return this.reaccionPostular26;
	}

	public void setReaccionPostular26(ReaccionPostular reaccionPostular26) {
		this.reaccionPostular26 = reaccionPostular26;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "respuestamenazaderid", nullable = false)
	public ReaccionPostular getReaccionPostular27() {
		return this.reaccionPostular27;
	}

	public void setReaccionPostular27(ReaccionPostular reaccionPostular27) {
		this.reaccionPostular27 = reaccionPostular27;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tamannopupilarizqid", nullable = false)
	public ReaccionPostular getReaccionPostular28() {
		return this.reaccionPostular28;
	}

	public void setReaccionPostular28(ReaccionPostular reaccionPostular28) {
		this.reaccionPostular28 = reaccionPostular28;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tamannopupilarderid", nullable = false)
	public ReaccionPostular getReaccionPostular29() {
		return this.reaccionPostular29;
	}

	public void setReaccionPostular29(ReaccionPostular reaccionPostular29) {
		this.reaccionPostular29 = reaccionPostular29;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "respuestapupilarizqid", nullable = false)
	public ReaccionPostular getReaccionPostular30() {
		return this.reaccionPostular30;
	}

	public void setReaccionPostular30(ReaccionPostular reaccionPostular30) {
		this.reaccionPostular30 = reaccionPostular30;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "respuestapupilarderid", nullable = false)
	public ReaccionPostular getReaccionPostular31() {
		return this.reaccionPostular31;
	}

	public void setReaccionPostular31(ReaccionPostular reaccionPostular31) {
		this.reaccionPostular31 = reaccionPostular31;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estrabismoreposoizqid", nullable = false)
	public ReaccionPostular getReaccionPostular32() {
		return this.reaccionPostular32;
	}

	public void setReaccionPostular32(ReaccionPostular reaccionPostular32) {
		this.reaccionPostular32 = reaccionPostular32;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estrabismoreposoderid", nullable = false)
	public ReaccionPostular getReaccionPostular33() {
		return this.reaccionPostular33;
	}

	public void setReaccionPostular33(ReaccionPostular reaccionPostular33) {
		this.reaccionPostular33 = reaccionPostular33;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estrabismoposicionalizqid", nullable = false)
	public ReaccionPostular getReaccionPostular34() {
		return this.reaccionPostular34;
	}

	public void setReaccionPostular34(ReaccionPostular reaccionPostular34) {
		this.reaccionPostular34 = reaccionPostular34;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estrabismoposicionalderid", nullable = false)
	public ReaccionPostular getReaccionPostular35() {
		return this.reaccionPostular35;
	}

	public void setReaccionPostular35(ReaccionPostular reaccionPostular35) {
		this.reaccionPostular35 = reaccionPostular35;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nistagmoizqid", nullable = false)
	public ReaccionPostular getReaccionPostular36() {
		return this.reaccionPostular36;
	}

	public void setReaccionPostular36(ReaccionPostular reaccionPostular36) {
		this.reaccionPostular36 = reaccionPostular36;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nistagmoderid", nullable = false)
	public ReaccionPostular getReaccionPostular37() {
		return this.reaccionPostular37;
	}

	public void setReaccionPostular37(ReaccionPostular reaccionPostular37) {
		this.reaccionPostular37 = reaccionPostular37;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "oculovestibularizqid", nullable = false)
	public ReaccionPostular getReaccionPostular38() {
		return this.reaccionPostular38;
	}

	public void setReaccionPostular38(ReaccionPostular reaccionPostular38) {
		this.reaccionPostular38 = reaccionPostular38;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "oculovestibularderid", nullable = false)
	public ReaccionPostular getReaccionPostular39() {
		return this.reaccionPostular39;
	}

	public void setReaccionPostular39(ReaccionPostular reaccionPostular39) {
		this.reaccionPostular39 = reaccionPostular39;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sensibilidadfacializqid", nullable = false)
	public ReaccionPostular getReaccionPostular40() {
		return this.reaccionPostular40;
	}

	public void setReaccionPostular40(ReaccionPostular reaccionPostular40) {
		this.reaccionPostular40 = reaccionPostular40;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sensibilidadfacialderid", nullable = false)
	public ReaccionPostular getReaccionPostular41() {
		return this.reaccionPostular41;
	}

	public void setReaccionPostular41(ReaccionPostular reaccionPostular41) {
		this.reaccionPostular41 = reaccionPostular41;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "masticacionizqid", nullable = false)
	public ReaccionPostular getReaccionPostular42() {
		return this.reaccionPostular42;
	}

	public void setReaccionPostular42(ReaccionPostular reaccionPostular42) {
		this.reaccionPostular42 = reaccionPostular42;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "masticacionderid", nullable = false)
	public ReaccionPostular getReaccionPostular43() {
		return this.reaccionPostular43;
	}

	public void setReaccionPostular43(ReaccionPostular reaccionPostular43) {
		this.reaccionPostular43 = reaccionPostular43;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sensibilidadocularizqid", nullable = false)
	public ReaccionPostular getReaccionPostular44() {
		return this.reaccionPostular44;
	}

	public void setReaccionPostular44(ReaccionPostular reaccionPostular44) {
		this.reaccionPostular44 = reaccionPostular44;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sensibilidadocularderid", nullable = false)
	public ReaccionPostular getReaccionPostular45() {
		return this.reaccionPostular45;
	}

	public void setReaccionPostular45(ReaccionPostular reaccionPostular45) {
		this.reaccionPostular45 = reaccionPostular45;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "palpebralizqid", nullable = false)
	public ReaccionPostular getReaccionPostular46() {
		return this.reaccionPostular46;
	}

	public void setReaccionPostular46(ReaccionPostular reaccionPostular46) {
		this.reaccionPostular46 = reaccionPostular46;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "palpebralderid", nullable = false)
	public ReaccionPostular getReaccionPostular47() {
		return this.reaccionPostular47;
	}

	public void setReaccionPostular47(ReaccionPostular reaccionPostular47) {
		this.reaccionPostular47 = reaccionPostular47;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "deglucionizqid", nullable = false)
	public ReaccionPostular getReaccionPostular48() {
		return this.reaccionPostular48;
	}

	public void setReaccionPostular48(ReaccionPostular reaccionPostular48) {
		this.reaccionPostular48 = reaccionPostular48;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "deglucionderid", nullable = false)
	public ReaccionPostular getReaccionPostular49() {
		return this.reaccionPostular49;
	}

	public void setReaccionPostular49(ReaccionPostular reaccionPostular49) {
		this.reaccionPostular49 = reaccionPostular49;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "lenguaizqid", nullable = false)
	public ReaccionPostular getReaccionPostular50() {
		return this.reaccionPostular50;
	}

	public void setReaccionPostular50(ReaccionPostular reaccionPostular50) {
		this.reaccionPostular50 = reaccionPostular50;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "lenguaderid", nullable = false)
	public ReaccionPostular getReaccionPostular51() {
		return this.reaccionPostular51;
	}

	public void setReaccionPostular51(ReaccionPostular reaccionPostular51) {
		this.reaccionPostular51 = reaccionPostular51;
	}	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bicepsizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal() {
		return this.reflejoEspinal;
	}

	public void setReflejoEspinal(ReflejoEspinal reflejoEspinal) {
		this.reflejoEspinal = reflejoEspinal;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bicepsderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal1() {
		return this.reflejoEspinal1;
	}

	public void setReflejoEspinal1(ReflejoEspinal reflejoEspinal1) {
		this.reflejoEspinal1 = reflejoEspinal1;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tricepsizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal2() {
		return this.reflejoEspinal2;
	}

	public void setReflejoEspinal2(ReflejoEspinal reflejoEspinal2) {
		this.reflejoEspinal2 = reflejoEspinal2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tricepsderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal3() {
		return this.reflejoEspinal3;
	}

	public void setReflejoEspinal3(ReflejoEspinal reflejoEspinal3) {
		this.reflejoEspinal3 = reflejoEspinal3;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorcarporadializqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal4() {
		return this.reflejoEspinal4;
	}

	public void setReflejoEspinal4(ReflejoEspinal reflejoEspinal4) {
		this.reflejoEspinal4 = reflejoEspinal4;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "extensorcarporadialderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal5() {
		return this.reflejoEspinal5;
	}

	public void setReflejoEspinal5(ReflejoEspinal reflejoEspinal5) {
		this.reflejoEspinal5 = reflejoEspinal5;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flexortoracicoizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal6() {
		return this.reflejoEspinal6;
	}

	public void setReflejoEspinal6(ReflejoEspinal reflejoEspinal6) {
		this.reflejoEspinal6 = reflejoEspinal6;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flexortoracicoderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal7() {
		return this.reflejoEspinal7;
	}

	public void setReflejoEspinal7(ReflejoEspinal reflejoEspinal7) {
		this.reflejoEspinal7 = reflejoEspinal7;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patelarizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal8() {
		return this.reflejoEspinal8;
	}

	public void setReflejoEspinal8(ReflejoEspinal reflejoEspinal8) {
		this.reflejoEspinal8 = reflejoEspinal8;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patelarderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal9() {
		return this.reflejoEspinal9;
	}

	public void setReflejoEspinal9(ReflejoEspinal reflejoEspinal9) {
		this.reflejoEspinal9 = reflejoEspinal9;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tibialcranealizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal10() {
		return this.reflejoEspinal10;
	}

	public void setReflejoEspinal10(ReflejoEspinal reflejoEspinal10) {
		this.reflejoEspinal10 = reflejoEspinal10;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tibialcranealderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal11() {
		return this.reflejoEspinal11;
	}

	public void setReflejoEspinal11(ReflejoEspinal reflejoEspinal11) {
		this.reflejoEspinal11 = reflejoEspinal11;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gastrocnemioizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal12() {
		return this.reflejoEspinal12;
	}

	public void setReflejoEspinal12(ReflejoEspinal reflejoEspinal12) {
		this.reflejoEspinal12 = reflejoEspinal12;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gastrocnemioderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal13() {
		return this.reflejoEspinal13;
	}

	public void setReflejoEspinal13(ReflejoEspinal reflejoEspinal13) {
		this.reflejoEspinal13 = reflejoEspinal13;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flexorpelvicoizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal14() {
		return this.reflejoEspinal14;
	}

	public void setReflejoEspinal14(ReflejoEspinal reflejoEspinal14) {
		this.reflejoEspinal14 = reflejoEspinal14;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flexorpelvicoderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal15() {
		return this.reflejoEspinal15;
	}

	public void setReflejoEspinal15(ReflejoEspinal reflejoEspinal15) {
		this.reflejoEspinal15 = reflejoEspinal15;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "perinealizqid", nullable = false)
	public ReflejoEspinal getReflejoEspinal16() {
		return this.reflejoEspinal16;
	}

	public void setReflejoEspinal16(ReflejoEspinal reflejoEspinal16) {
		this.reflejoEspinal16 = reflejoEspinal16;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "perinealderid", nullable = false)
	public ReflejoEspinal getReflejoEspinal17() {
		return reflejoEspinal17;
	}

	public void setReflejoEspinal17(ReflejoEspinal reflejoEspinal17) {
		this.reflejoEspinal17 = reflejoEspinal17;
	}	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "atrofiaid", nullable = false)
	public Dolor getDolor2() {
		return this.dolor2;
	}

	public void setDolor2(Dolor dolor2) {
		this.dolor2 = dolor2;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "dolorprofundoid", nullable = false)
	public Dolor getDolor3() {
		return this.dolor3;
	}

	public void setDolor3(Dolor dolor3) {
		this.dolor3 = dolor3;
	}	

	@JoinColumn(name = "hiperestesiacervical", nullable = false)
	public Boolean getCervical() {
		return cervical;
	}

	public void setCervical(Boolean cervical) {
		this.cervical = cervical;
	}	

	@JoinColumn(name = "hiperestesiatoracica", nullable = false)
	public Boolean getToracica() {
		return toracica;
	}

	public void setToracica(Boolean toracica) {
		this.toracica = toracica;
	}

	@JoinColumn(name = "hiperestesiatoracolumbar", nullable = false)
	public Boolean getToracolumbar() {
		return toracolumbar;
	}

	public void setToracolumbar(Boolean toracolumbar) {
		this.toracolumbar = toracolumbar;
	}

	@JoinColumn(name = "hiperestesialumbar", nullable = false)
	public Boolean getLumbar() {
		return lumbar;
	}

	public void setLumbar(Boolean lumbar) {
		this.lumbar = lumbar;
	}

	@JoinColumn(name = "hiperestesialumbosacra", nullable = false)
	public Boolean getLumbosacra() {
		return lumbosacra;
	}

	public void setLumbosacra(Boolean lumbosacra) {
		this.lumbosacra = lumbosacra;
	}

	@JoinColumn(name = "hiperestesiacaudal", nullable = false)
	public Boolean getCaudal() {
		return caudal;
	}

	public void setCaudal(Boolean caudal) {
		this.caudal = caudal;
	}

	@JoinColumn(name = "hiperestesianinguna", nullable = false)
	public Boolean getNinguna() {
		return ninguna;
	}

	public void setNinguna(Boolean ninguna) {
		this.ninguna = ninguna;
	}

	@JoinColumn(name = "hiperestesiaotra", nullable = false)
	public Boolean getOtra() {
		return otra;
	}

	public void setOtra(Boolean otra) {
		this.otra = otra;
	}

	@JoinColumn(name = "cutaneatronconormal", nullable = false)
	public String getCutaneaTroncoNormal() {
		return cutaneaTroncoNormal;
	}

	public void setCutaneaTroncoNormal(String cutaneaTroncoNormal) {
		this.cutaneaTroncoNormal = cutaneaTroncoNormal;
	}

	public String getTratamientoIndicaciones() {
		return tratamientoIndicaciones;
	}

	public void setTratamientoIndicaciones(String tratamientoIndicaciones) {
		this.tratamientoIndicaciones = tratamientoIndicaciones;
	}

	public String getTratamientoAplicado() {
		return tratamientoAplicado;
	}

	public void setTratamientoAplicado(String tratamientoAplicado) {
		this.tratamientoAplicado = tratamientoAplicado;
	}

	public String getTratamientoEnviado() {
		return tratamientoEnviado;
	}

	public void setTratamientoEnviado(String tratamientoEnviado) {
		this.tratamientoEnviado = tratamientoEnviado;
	}

	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getPatologiaComentario() {
		return patologiaComentario;
	}

	public void setPatologiaComentario(String patologiaComentario) {
		this.patologiaComentario = patologiaComentario;
	}

	public String getDiagnosticoDiferencial() {
		return diagnosticoDiferencial;
	}

	public void setDiagnosticoDiferencial(String diagnosticoDiferencial) {
		this.diagnosticoDiferencial = diagnosticoDiferencial;
	}

	public String getDiagnosticoDefinitivo() {
		return diagnosticoDefinitivo;
	}

	public void setDiagnosticoDefinitivo(String diagnosticoDefinitivo) {
		this.diagnosticoDefinitivo = diagnosticoDefinitivo;
	}

	public String getDiagnosticoTentativo() {
		return diagnosticoTentativo;
	}

	public void setDiagnosticoTentativo(String diagnosticoTentativo) {
		this.diagnosticoTentativo = diagnosticoTentativo;
	}

	public String getDiagnosticoProcedimiento() {
		return diagnosticoProcedimiento;
	}

	public void setDiagnosticoProcedimiento(String diagnosticoProcedimiento) {
		this.diagnosticoProcedimiento = diagnosticoProcedimiento;
	}
	
	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}
	
	public Neurologia() {
		super.setTipoServicio(new TipoServicio("NEU"));
	}

	public Neurologia(int id, int status, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("NEU"));
	}

	@Override
	public String toString() {
		return "Modelo Neurologia,  id: " + super.getId();
	}

}
