package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * PatronDistribucion generated by hbm2java
 */
@Entity
@Table(name = "patron_distribucion", schema = "public")
public class PatronDistribucion implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';
	private Set<Dermatologia> dermatologias = new HashSet<Dermatologia>(0);

	public PatronDistribucion() {
	}

	public PatronDistribucion(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_PATRONDISTRIBUCION", sequenceName = "seq_patrondistribucion", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_PATRONDISTRIBUCION")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dermatologia_patrondistribucion", schema = "public", joinColumns = { @JoinColumn(name = "patrondistribucionid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dermatologia_patrid", nullable = false, updatable = false) })
	public Set<Dermatologia> getDermatologias() {
		return dermatologias;
	}

	public void setDermatologias(Set<Dermatologia> dermatologias) {
		this.dermatologias = dermatologias;
	}
	
	@Override
	public boolean equals(Object obj) {
		PatronDistribucion comparacion = (PatronDistribucion) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo PatronDistribucion, id: " + id;
	}

}
