package org.ucla.sigma.modelo;

// Generated 23/06/2012 10:22:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private char estatus = 'A';
	private Set<Funcion> funcions = new HashSet<Funcion>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Perfil() {
	}

	public Perfil(int id, String nombre, String descripcion, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public Perfil(int id, String nombre, String descripcion, char estatus,
			Set<Funcion> funcions, Set<Usuario> usuarios) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.funcions = funcions;
		this.usuarios = usuarios;
	}

	@Id
	@SequenceGenerator(name = "SEQ_PERFIL", sequenceName = "seq_perfil", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_PERFIL")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "perfil_funcion", schema = "public", joinColumns = { @JoinColumn(name = "perfilid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "funcionid", nullable = false, updatable = false) })
	@Fetch(FetchMode.SUBSELECT)
	public Set<Funcion> getFuncions() {
		return this.funcions;
	}

	public void setFuncions(Set<Funcion> funcions) {
		this.funcions = funcions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_perfil", schema = "public", joinColumns = { @JoinColumn(name = "perfilid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "usuariocedula", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
	
	@Override
	public boolean equals(Object obj) {
		Perfil comparacion = (Perfil) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Perfil, id: " + id;
	}

}
