package org.ucla.sigma.modelo;

// Generated 09/06/2012 02:25:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PostOperatorio generated by hbm2java
 */
@Entity
@Table(name = "post_operatorio", schema = "public")
public class PostOperatorio extends Historial implements java.io.Serializable {

	public PostOperatorio() {
		super.setTipoServicio(new TipoServicio("PTO"));
	}

	public PostOperatorio(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("PTO"));
	}

	@Override
	public String toString() {
		return "Modelo PostOperatorio, id: " + super.getId();
	}

}
