package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Radiografia generated by hbm2java
 */
@Entity
@Table(name = "radiografia", schema = "public")
public class Radiografia implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';

	public Radiografia() {
	}

	public Radiografia(int id, String nombre, char estatus) {
		super();
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_RADIOGRAFIA", sequenceName = "seq_radiografia", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_RADIOGRAFIA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column( name = "nombre", nullable = false)
	public String getNombre() {
		return nombre;
	}
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column ( name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return estatus;
	}
	
	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Override
	public boolean equals(Object obj) {
		Radiografia comparacion = (Radiografia) obj;
		return comparacion.getId() == id;
	}

	
	@Override
	public String toString() {
		return "Modelo Radiografia, id: " + id;
	}

}
