package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * ReferenciaImagenologia generated by hbm2java
 */
@Entity
@Table(name = "referencia_imagenologia", schema = "public")
public class ReferenciaImagenologia extends Referencia implements
		java.io.Serializable {

	private Set<EspImagenologia> espImagenologias = new HashSet<EspImagenologia>(0);
	private String comentarios;
	
	public ReferenciaImagenologia() {
		super.setTipoReferencia(new TipoReferencia("RIM"));
	}

	public ReferenciaImagenologia(Referencia referencia) {
		super.setTipoReferencia(new TipoReferencia("RIM"));
	}

	public ReferenciaImagenologia(int id, Historial historial,
			TipoReferencia tipoReferencia, TipoServicio tipoServicio,
			Date fechaExpedicion) {
		super.setId(id);
		super.setHistorial(historial);
		super.setTipoReferencia(tipoReferencia);
		super.setTipoServicio(tipoServicio);
		super.setFechaExpedicion(fechaExpedicion);
		super.setTipoReferencia(new TipoReferencia("RIM"));
	}
	
	
	@ManyToMany(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SUBSELECT)
	@JoinTable(name = "referencia_imagenologia_esp_imagenologia", schema = "public", joinColumns = { @JoinColumn(name = "referencia_imagenologiaid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "especificacion_imagenologiaid", nullable = false, updatable = false) })
	public Set<EspImagenologia> getEspImagenologias() {
		return espImagenologias;
	}

	public void setEspImagenologias(Set<EspImagenologia> espImagenologias) {
		this.espImagenologias = espImagenologias;
	}

	@Override
	public String toString() {
		return "Modelo ReferenciaImagenologia, id: " + super.getId();
	}

	

	
	
}
