package org.ucla.sigma.modelo;

// Generated 09/06/2012 11:00:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReferenciaLaboratorio generated by hbm2java
 */
@Entity
@Table(name = "referencia_laboratorio", schema = "public")
public class ReferenciaLaboratorio extends Referencia implements
		java.io.Serializable {

	public ReferenciaLaboratorio() {
		super.setTipoReferencia(new TipoReferencia("RLB"));
	}

	public ReferenciaLaboratorio(Referencia referencia) {
		super.setTipoReferencia(new TipoReferencia("RLB"));
	}

	public ReferenciaLaboratorio(int id, Historial historial,
			TipoReferencia tipoReferencia, TipoServicio tipoServicio,
			Date fechaExpedicion) {
		super.setId(id);
		super.setHistorial(historial);
		super.setTipoReferencia(tipoReferencia);
		super.setTipoServicio(tipoServicio);
		super.setFechaExpedicion(fechaExpedicion);
		super.setTipoReferencia(new TipoReferencia("RLB"));
	}

	@Override
	public String toString() {
		return "Modelo ReferenciaLaboratorio, id: " + super.getId();
	}

}
