package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReferenciaCirugia generated by hbm2java
 */


	

@Entity
@Table(name = "referencia_cirugia", schema = "public")
public class ReferenciaCirugia extends Referencia implements
		java.io.Serializable {

	
	private String comentarios;
	
	public ReferenciaCirugia() {
		super.setTipoReferencia(new TipoReferencia("RCI"));
	}

	public ReferenciaCirugia(Referencia referencia) {
		super.setTipoReferencia(new TipoReferencia("RCI"));
	}

	public ReferenciaCirugia(int id, Historial historial,
			TipoReferencia tipoReferencia, TipoServicio tipoServicio,
			Date fechaExpedicion) {
		super.setId(id);
		super.setHistorial(historial);
		super.setTipoReferencia(tipoReferencia);
		super.setTipoServicio(tipoServicio);
		super.setFechaExpedicion(fechaExpedicion);
		super.setTipoReferencia(new TipoReferencia("RCI"));
	}

	@Override
	public String toString() {
		return "Modelo ReferenciaCirugia, id: " + super.getId();
	}
	
	@Column(name = "comentarios", nullable = false)
	public String getComentarios() {
		return comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}
	

}
