package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "reflejo", schema = "public")
public class Reflejo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<Oftalmologia> oftalmologiasIzq = new HashSet<Oftalmologia>(0);
	private Set<Oftalmologia> oftalmologiasDer = new HashSet<Oftalmologia>(0);
	
	private char estatus = 'A';
	

	public Reflejo() {
	}

	public Reflejo(int id,  char estatus) {
		this.id = id;
		
		this.estatus = estatus;
	}

	public Reflejo(int id, String nombre, char estatus
			) {
		this.id = id;
		this.nombre = nombre;
		
		this.estatus = estatus;
		
	}

	@Id
	@SequenceGenerator(name = "SEQ_REFLEJO", sequenceName = "seq_reflejo", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_REFLEJO")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reflejoIzq")
	public Set<Oftalmologia> getOftalmologiasIzq() {
		return oftalmologiasIzq;
	}

	public void setOftalmologiasIzq(Set<Oftalmologia> oftalmologiasIzq) {
		this.oftalmologiasIzq = oftalmologiasIzq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reflejoDer")
	public Set<Oftalmologia> getOftalmologiasDer() {
		return oftalmologiasDer;
	}

	public void setOftalmologiasDer(Set<Oftalmologia> oftalmologiasDer) {
		this.oftalmologiasDer = oftalmologiasDer;
	}

	@Override
	public boolean equals(Object obj) {
		Reflejo comparacion = (Reflejo) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Reflejo, id: " + id;
	}

}
