package org.ucla.sigma.modelo;

// Generated 04/06/2012 10:59:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Respuesta generated by hbm2java
 */
@Entity
@Table(name = "respuesta", schema = "public")
public class Respuesta implements java.io.Serializable {

	private int id;
	private Notificacion notificacion;
	private Usuario usuario;
	private String texto;
	private Date creacion;
	private char estatus = 'A';

	public Respuesta() {
	}

	public Respuesta(int id, Notificacion notificacion, Usuario usuario,
			String texto, Date creacion, char estatus) {
		this.id = id;
		this.notificacion = notificacion;
		this.usuario = usuario;
		this.texto = texto;
		this.creacion = creacion;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_RESPUESTA", sequenceName = "seq_respuesta", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_RESPUESTA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notificacionid", nullable = false)
	public Notificacion getNotificacion() {
		return this.notificacion;
	}

	public void setNotificacion(Notificacion notificacion) {
		this.notificacion = notificacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usuariocedula", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "texto", nullable = false, columnDefinition = "text")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Override
	public boolean equals(Object obj) {
		Respuesta comparacion = (Respuesta) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Respuesta, id: " + id;
	}

}
