package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", schema = "public")
public class Servicio implements java.io.Serializable {

	private int id;
	private TipoServicio tipoServicio;
	private String nombre;
	private String descripcion;
	private char estatus = 'A';
	private Set<Historial> historials = new HashSet<Historial>(0);

	public Servicio() {
	}

	public Servicio(int id, TipoServicio tipoServicio, String nombre,
			char estatus) {
		this.id = id;
		this.tipoServicio = tipoServicio;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Servicio(int id, TipoServicio tipoServicio, String nombre,
			String descripcion, char estatus, Set<Historial> historials) {
		this.id = id;
		this.tipoServicio = tipoServicio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.historials = historials;
	}

	@Id
	@SequenceGenerator(name = "SEQ_SERVICIO", sequenceName = "seq_servicio", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_SERVICIO")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_servicioid", nullable = false)
	public TipoServicio getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(TipoServicio tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "historial_servicio", schema = "public", joinColumns = { @JoinColumn(name = "servicioid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "historialid", nullable = false, updatable = false) })
	public Set<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set<Historial> historials) {
		this.historials = historials;
	}

	@Override
	public boolean equals(Object obj) {
		Servicio comparacion = (Servicio) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Servicio, id: " + id;
	}

}
