package org.ucla.sigma.modelo;

// Generated 09/06/2012 11:00:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * Sintoma generated by hbm2java
 */
@Entity
@Table(name = "sintoma", schema = "public")
public class Sintoma implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';
	private Set<Historial> historials = new HashSet<Historial>(0);

	public Sintoma() {
	}

	public Sintoma(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Sintoma(int id, String nombre, char estatus, Set<Historial> historials) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
		this.historials = historials;
	}

	@Id
	@SequenceGenerator(name = "SEQ_SINTOMA", sequenceName = "seq_sintoma", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_SINTOMA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "historial_sintoma", schema = "public", joinColumns = { @JoinColumn(name = "sintomaid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "historialid", nullable = false, updatable = false) })
	public Set<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set<Historial> historials) {
		this.historials = historials;
	}

	@Override
	public boolean equals(Object obj) {
		Sintoma comparacion = (Sintoma) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Sintoma, id: " + id;
	}

}
