package org.ucla.sigma.modelo;

// Generated 03/06/2012 11:28:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suscripcion generated by hbm2java
 */
@Entity
@Table(name = "suscripcion", schema = "public")
public class Suscripcion implements java.io.Serializable {

	private int id;
	private String nombre;
	private String correo;
	private Date creacion;
	private char estatus = 'A';
	private Set<TipoPublicacion> tipoPublicacions = new HashSet<TipoPublicacion>(
			0);

	public Suscripcion() {
	}

	public Suscripcion(int id, String nombre, String correo, Date creacion,
			char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.correo = correo;
		this.creacion = creacion;
		this.estatus = estatus;
	}

	public Suscripcion(int id, String nombre, String correo, Date creacion,
			char estatus, Set<TipoPublicacion> tipoPublicacions) {
		this.id = id;
		this.nombre = nombre;
		this.correo = correo;
		this.creacion = creacion;
		this.estatus = estatus;
		this.tipoPublicacions = tipoPublicacions;
	}

	@Id
	@SequenceGenerator(name = "SEQ_SUSCRIPCION", sequenceName = "seq_suscripcion", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_SUSCRIPCION")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "correo", nullable = false)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "suscripcion_tipo_publicacion", schema = "public", joinColumns = { @JoinColumn(name = "suscripcionid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "tipo_publicacionid", nullable = false, updatable = false) })
	public Set<TipoPublicacion> getTipoPublicacions() {
		return this.tipoPublicacions;
	}

	public void setTipoPublicacions(Set<TipoPublicacion> tipoPublicacions) {
		this.tipoPublicacions = tipoPublicacions;
	}

	@Override
	public boolean equals(Object obj) {
		Suscripcion comparacion = (Suscripcion) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Suscripcion, id: " + id;
	}

}
