package org.ucla.sigma.modelo;

// Generated 09/06/2012 02:25:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * TipoDefuncion generated by hbm2java
 */
@Entity
@Table(name = "tipo_defuncion", schema = "public")
public class TipoDefuncion implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus = 'A';
	private Set<Defuncion> defuncions = new HashSet<Defuncion>(0);

	public TipoDefuncion() {
	}

	public TipoDefuncion(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public TipoDefuncion(int id, String nombre, char estatus,
			Set<Defuncion> defuncions) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
		this.defuncions = defuncions;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TIPO_DEFUNCION", sequenceName = "seq_tipo_defuncion", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TIPO_DEFUNCION")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDefuncion")
	public Set<Defuncion> getDefuncions() {
		return this.defuncions;
	}

	public void setDefuncions(Set<Defuncion> defuncions) {
		this.defuncions = defuncions;
	}

	@Override
	public boolean equals(Object obj) {
		TipoDefuncion comparacion = (TipoDefuncion) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo TipoDefuncion, id: " + id;
	}

}
