package org.ucla.sigma.modelo;

// Generated 01/07/2012 10:01:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TipoServicioWeb generated by hbm2java
 */
@Entity
@Table(name = "tipo_servicio_web", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uri"))
public class TipoServicioWeb implements java.io.Serializable {

	private int id;
	private TipoServicio tipoServicio;
	private String uri;
	private String descripcion;
	private char estatus = 'A';

	public TipoServicioWeb() {
	}

	public TipoServicioWeb(int id, TipoServicio tipoServicio, String uri,
			String descripcion, char estatus) {
		this.id = id;
		this.tipoServicio = tipoServicio;
		this.uri = uri;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TIPO_SERVICIO_WEB", sequenceName = "seq_tipo_servicio_web", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TIPO_SERVICIO_WEB")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_servicioid", nullable = false)
	public TipoServicio getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(TipoServicio tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	@Column(name = "uri", unique = true, nullable = false)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "descripcion", nullable = false, columnDefinition = "text")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Override
	public boolean equals(Object obj) {
		TipoServicioWeb comparacion = (TipoServicioWeb) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo TipoServicioWeb, id: " + id;
	}

}
