package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * TipoTratamiento generated by hbm2java
 */
@Entity
@Table(name = "tipo_tratamiento", schema = "public")
public class TipoTratamiento implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus='A';
	private Set<Tratamiento> tratamientos = new HashSet<Tratamiento>(0);

	public TipoTratamiento() {
	}

	public TipoTratamiento(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public TipoTratamiento(int id, String nombre, char estatus,
			Set<Tratamiento> tratamientos) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
		this.tratamientos = tratamientos;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TIPO_TRATAMIENTO", sequenceName = "seq_tipo_tratamiento", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TIPO_TRATAMIENTO")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTratamiento")
	public Set<Tratamiento> getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set<Tratamiento> tratamientos) {
		this.tratamientos = tratamientos;
	}
	
	@Override
	public boolean equals(Object obj) {
		TipoTratamiento comparacion = (TipoTratamiento) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo TipoTratamiento, id: " + id;
	}

}
