package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * TipoPatologia generated by hbm2java
 */
@Entity
@Table(name = "tipo_patologia", schema = "public")
public class TipoPatologia implements java.io.Serializable {

	private int id;
	private String nombre;
	private char estatus ='A';
	private Set<Patologia> patologias = new HashSet<Patologia>(0);

	public TipoPatologia() {
	}

	public TipoPatologia(int id, String nombre, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public TipoPatologia(int id, String nombre, char estatus,
			Set<Patologia> patologias) {
		this.id = id;
		this.nombre = nombre;
		this.estatus = estatus;
		this.patologias = patologias;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TIPO_PATOLOGIA", sequenceName = "seq_tipo_patologia", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TIPO_PATOLOGIA")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPatologia")
	public Set<Patologia> getPatologias() {
		return this.patologias;
	}

	public void setPatologias(Set<Patologia> patologias) {
		this.patologias = patologias;
	}
	
	@Override
	public boolean equals(Object obj) {
		TipoPatologia comparacion = (TipoPatologia) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo TipoPatologia, id: " + id;
	}

}
