package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * Tratamiento generated by hbm2java
 */
@Entity
@Table(name = "tratamiento", schema = "public")
public class Tratamiento implements java.io.Serializable {

	private int id;
	private TipoTratamiento tipoTratamiento;
	private String nombre;
	private char estatus = 'A';
	private Set<Historial> historials = new HashSet<Historial>(0);

	public Tratamiento() {
	}

	public Tratamiento(int id, TipoTratamiento tipoTratamiento, String nombre,
			char estatus) {
		this.id = id;
		this.tipoTratamiento = tipoTratamiento;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Tratamiento(int id, TipoTratamiento tipoTratamiento, String nombre,
			char estatus, Set<Historial> historials) {
		this.id = id;
		this.tipoTratamiento = tipoTratamiento;
		this.nombre = nombre;
		this.estatus = estatus;
		this.historials = historials;
	}

	@Id
	@SequenceGenerator(name = "SEQ_TRATAMIENTO", sequenceName = "seq_tratamiento", allocationSize = 1, schema = "public")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TRATAMIENTO")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_tratamientoid", nullable = false)
	public TipoTratamiento getTipoTratamiento() {
		return this.tipoTratamiento;
	}

	public void setTipoTratamiento(TipoTratamiento tipoTratamiento) {
		this.tipoTratamiento = tipoTratamiento;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "historial_tratamiento", schema = "public", joinColumns = { @JoinColumn(name = "tratamientoid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "historialid", nullable = false, updatable = false) })
	public Set<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set<Historial> historials) {
		this.historials = historials;
	}

	@Override
	public boolean equals(Object obj) {
		Tratamiento comparacion = (Tratamiento) obj;
		return comparacion.getId() == id;
	}

	@Override
	public String toString() {
		return "Modelo Tratamiento, id: " + id;
	}

}
