package org.ucla.sigma.modelo;

// Generated 09/06/2012 03:00:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Traumatologia generated by hbm2java
 */
@Entity
@Table(name = "traumatologia", schema = "public")
public class Traumatologia extends Historial implements java.io.Serializable {

	public Traumatologia() {
		super.setTipoServicio(new TipoServicio("TRA"));
	}

	public Traumatologia(int id, Paciente paciente, Veterinario veterinario,
			Date fecha, Date hora) {
		super.setId(id);
		super.setPaciente(paciente);
		super.setVeterinario(veterinario);
		super.setFecha(fecha);
		super.setHora(hora);
		super.setTipoServicio(new TipoServicio("TRA"));
	}

	@Override
	public String toString() {
		return "Modelo Traumatologia,  id: " + super.getId();
	}

}
