create table especie (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table raza (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, especieid int4 not null, primary key (id));
create table sexo (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table paciente (historia_medica varchar(20) not null, nombre varchar(255) not null, fecha_nac date not null, creacion date not null, estatus char(1) not null, razaid int4 not null, sexoid int4 not null, responsablecedula int4 not null, primary key (historia_medica));
create table referencia_consulta_especializada (id int4 not null, primary key (id));
create table referencia_laboratorio (id int4 not null, primary key (id));
create table referencia_imagenologia (id int4 not null, primary key (id));
create table referencia_cirugia (id int4 not null, primary key (id));
create table referencia (id int4 not null, fecha_expedicion date not null, fecha_cita date, estatus char(1) not null, tipo_servicioid varchar(5) not null, historialid int4 not null, tipo_referenciaid varchar(5) not null, primary key (id));
comment on table referencia is 'fecha_expedicion: fecha en que se creo el registro
fecha_cita: fecha de cita, sera null cuando el medico la cree y tendra un fecha cuando la recepcionista haga la cita
tipo_servicioid: servicio al que fue referido';
create table dia_de_atencion (id int4 not null, max_citas int4 not null, estatus char(1) not null, diaid int4 not null, tipo_servicioid varchar(5) not null, primary key (id));
create table tipo_servicio (id varchar(5) not null, nombre varchar(255) not null, vista varchar(255) not null, estatus char(1) not null, primary key (id));
create table servicio (id int4 not null, nombre varchar(255) not null, descripcion varchar(255), estatus char(1) not null, tipo_servicioid varchar(5) not null, primary key (id));
create table area (id int4 not null, nombre varchar(255) not null, descripcion varchar(255), estatus char(1) not null, hospitalid int4 not null, primary key (id));
create table hospital (id int4 not null, nombre varchar(255) not null, descripcion varchar(255) not null, direccion varchar(255) not null, telefono_a varchar(12) not null, telefono_b varchar(12), correo_a varchar(255) not null, correo_b varchar(255), fax_a varchar(12), fax_b varchar(12), twitter varchar(255), rif varchar(20), nit varchar(20), mision text not null, vision text not null, objetivo text not null, slogan text not null, horario varchar(255) not null, estatus char(1) not null, ciudadid int4 not null, imagenid int4, primary key (id));
create table estado (id int4 not null, nombre varchar(255) not null, abreviatura varchar(5) not null, estatus char(1) not null, primary key (id));
create table ciudad (id int4 not null, nombre varchar(255) not null, codigo_postal varchar(5), estatus char(1) not null, estadoid int4 not null, primary key (id));
create table veterinario (cedula int4 not null, numero_sanidad varchar(20), numero_colegio varchar(20), rif varchar(20), estatus char(1) not null, primary key (cedula));
create table persona (cedula int4 not null, nombre varchar(255) not null, apellido varchar(255) not null, direccion varchar(255), telefono varchar(12), correo varchar(255), estatus char(1) not null, ciudadid int4 not null, primary key (cedula));
create table tipo_entidad_externa (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table entidad_externa (id int4 not null, nombre varchar(255) not null, descripcion varchar(255), direccion varchar(255), telefono varchar(12), fax varchar(12), web varchar(255), correo varchar(255), rif varchar(20), nit varchar(20), estatus char(1) not null, imagenid int4, tipo_entidad_externaid int4 not null, ciudadid int4 not null, primary key (id));
create table mensaje (id varchar(20) not null, texto varchar(255) not null, tipo_mensajeid varchar(20) not null, primary key (id));
create table tipo_mensaje (id varchar(20) not null, titulo varchar(20) not null, icono varchar(255), primary key (id));
create table boton (id varchar(20) not null, label varchar(255) not null, valor int4 not null, primary key (id));
create table publicacion (id int4 not null, titulo varchar(255) not null, uri varchar(255) not null unique, texto text not null, creacion date not null, estatus char(1) not null, genero_publicacionid int4 not null, tipo_publicacionid int4 not null, usuariocedula int4 not null, imagenid int4, primary key (id));
create table tipo_publicacion (id int4 not null, nombre varchar(255) not null, uri varchar(255) not null unique, descripcion text, estatus char(1) not null, primary key (id));
comment on table tipo_publicacion is 'Se utiliza para clasificar las publicaciones en distintas áreas en la web, ejemplo: noticias, revista';
create table genero_publicacion (id int4 not null, nombre varchar(255) not null, descripcion text, estatus char(1) not null, primary key (id));
comment on table genero_publicacion is 'Ejemplo: Tecnología, salud';
create table imagen (id int4 not null, nombre varchar(255) not null, bytes bytea not null, extension varchar(5) not null, creacion date not null, estatus char(1) not null, primary key (id));
create table adjunto (id int4 not null, nombre varchar(255) not null, bytes bytea not null, extension varchar(5) not null, creacion date not null, estatus char(1) not null, primary key (id));
create table publicacion_adjunto (publicacionid int4 not null, adjuntoid int4 not null, primary key (publicacionid, adjuntoid));
create table tipo_mensaje_boton (tipo_mensajeid varchar(20) not null, botonid varchar(20) not null, primary key (tipo_mensajeid, botonid));
create table publicidad (id int4 not null, titulo varchar(255) not null, descripcion varchar(255), creacion date not null, expiracion date, clicks int4, enlace varchar(255), activo bool not null, estatus char(1) not null, imagenid int4, primary key (id));
create table difusion (id int4 not null, nombre varchar(255) not null, enlace varchar(255) not null, estatus char(1) not null, imagenid int4, primary key (id));
create table hospital_difusion (id int4 not null, enlace varchar(255) not null, estatus char(1) not null, hospitalid int4 not null, difusionid int4 not null, primary key (id));
create table suscripcion (id int4 not null, nombre varchar(255) not null, correo varchar(255) not null, creacion date not null, estatus char(1) not null, primary key (id));
create table notificacion (id int4 not null, nombre varchar(255) not null, apellido varchar(255) not null, correo varchar(255) not null, telefono varchar(12), texto text not null, creacion date not null, estatus char(1) not null, primary key (id));
create table respuesta (id int4 not null, texto text not null, creacion date not null, estatus char(1) not null, usuariocedula int4 not null, notificacionid int4 not null, primary key (id));
create table boletin_informativo (id int4 not null, titulo varchar(255) not null, texto text, creacion date not null, envio date, enviado bool not null, estatus char(1) not null, primary key (id));
create table boletin_informativo_publicacion (boletin_informativoid int4 not null, publicacionid int4 not null, primary key (boletin_informativoid, publicacionid));
create table suscripcion_tipo_publicacion (tipo_publicacionid int4 not null, suscripcionid int4 not null, primary key (tipo_publicacionid, suscripcionid));
create table usuario (cedula int4 not null, login varchar(20) not null unique, password varchar(8) not null, estatus char(1) not null, primary key (cedula));
create table recepcionista (cedula int4 not null, estatus char(1) not null, primary key (cedula));
create table responsable (cedula int4 not null, estatus char(1) not null, primary key (cedula));
create table historial (id int4 not null, fecha date not null, hora time(7) not null, estatus char(1) not null, pacientehistoria_medica varchar(20) not null, veterinariocedula int4 not null, tipo_servicioid varchar(5) not null, primary key (id));
create table defuncion (id int4 not null, tipo_defuncionid int4 not null, primary key (id));
create table ficha_medica (id int4 not null, primary key (id));
create table consulta_general (id int4 not null, primary key (id));
create table dermatologia (id int4 not null, primary key (id));
create table cardiologia (id int4 not null, primary key (id));
create table oftalmologia (id int4 not null, primary key (id));
create table neurologia (id int4 not null, primary key (id));
create table sintoma (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table pre_operatorio (id int4 not null, primary key (id));
create table post_operatorio (id int4 not null, primary key (id));
create table historial_sintoma (historialid int4 not null, sintomaid int4 not null, primary key (historialid, sintomaid));
create table tratamiento (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, tipo_tratamientoid int4 not null, primary key (id));
create table tipo_tratamiento (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table historial_tratamiento (historialid int4 not null, tratamientoid int4 not null, primary key (historialid, tratamientoid));
create table patologia (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, tipo_patologiaid int4 not null, primary key (id));
create table historial_patologia (historialid int4 not null, patologiaid int4 not null, primary key (historialid, patologiaid));
create table carnet (id int4 not null, expedicion date not null, vencimiento date not null, estatus char(1) not null, pacientehistoria_medica varchar(20) not null, primary key (id));
create table tipo_patologia (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table tipo_defuncion (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table traumatologia (id int4 not null, primary key (id));
create table laboratorio (id int4 not null, primary key (id));
create table imagenologia (id int4 not null, primary key (id));
create table cirugia (id int4 not null, primary key (id));
create table tipo_referencia (id varchar(5) not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table dia (id int4 not null, nombre varchar(255) not null, estatus char(1) not null, primary key (id));
create table perfil (id int4 not null, nombre varchar(255) not null, descripcion varchar(255) not null, estatus char(1) not null, primary key (id));
create table usuario_perfil (usuariocedula int4 not null, perfilid int4 not null, primary key (usuariocedula, perfilid));
create table funcion (id varchar(5) not null, nombre varchar(255) not null, orden int4 not null, url varchar(255), need_veterinario bool not null, estatus char(1) not null, funcionid varchar(5), primary key (id));
create table perfil_funcion (perfilid int4 not null, funcionid varchar(5) not null, primary key (perfilid, funcionid));
create table historial_servicio (historialid int4 not null, servicioid int4 not null, primary key (historialid, servicioid));
create table tipo_servicio_web (id int4 not null, uri varchar(255) not null unique, descripcion text not null, estatus char(1) not null, tipo_servicioid varchar(5) not null, primary key (id));
create table tipo_referencia_tipo_servicio (tipo_referenciaid varchar(5) not null, tipo_servicioid varchar(5) not null, primary key (tipo_referenciaid, tipo_servicioid));
alter table raza add constraint FKraza202407 foreign key (especieid) references especie (id);
alter table paciente add constraint FKpaciente977311 foreign key (sexoid) references sexo (id);
alter table paciente add constraint FKpaciente288038 foreign key (razaid) references raza (id);
alter table referencia_consulta_especializada add constraint FKreferencia292651 foreign key (id) references referencia (id);
alter table referencia_laboratorio add constraint FKreferencia798085 foreign key (id) references referencia (id);
alter table referencia_imagenologia add constraint FKreferencia518507 foreign key (id) references referencia (id);
alter table referencia_cirugia add constraint FKreferencia953857 foreign key (id) references referencia (id);
alter table servicio add constraint FKservicio638579 foreign key (tipo_servicioid) references tipo_servicio (id);
alter table area add constraint FKarea64487 foreign key (hospitalid) references hospital (id);
alter table ciudad add constraint FKciudad244716 foreign key (estadoid) references estado (id);
alter table hospital add constraint FKhospital338211 foreign key (ciudadid) references ciudad (id);
alter table veterinario add constraint FKveterinari234519 foreign key (cedula) references persona (cedula);
alter table entidad_externa add constraint FKentidad_ex655737 foreign key (tipo_entidad_externaid) references tipo_entidad_externa (id);
alter table entidad_externa add constraint FKentidad_ex930843 foreign key (ciudadid) references ciudad (id);
alter table persona add constraint FKpersona525534 foreign key (ciudadid) references ciudad (id);
alter table referencia add constraint FKreferencia897489 foreign key (tipo_servicioid) references tipo_servicio (id);
alter table mensaje add constraint FKmensaje645839 foreign key (tipo_mensajeid) references tipo_mensaje (id);
alter table publicacion add constraint FKpublicacio820624 foreign key (tipo_publicacionid) references tipo_publicacion (id);
alter table publicacion add constraint FKpublicacio708566 foreign key (genero_publicacionid) references genero_publicacion (id);
alter table publicacion add constraint FKpublicacio405516 foreign key (imagenid) references imagen (id);
alter table publicacion_adjunto add constraint FKpublicacio989819 foreign key (publicacionid) references publicacion (id);
alter table publicacion_adjunto add constraint FKpublicacio261524 foreign key (adjuntoid) references adjunto (id);
alter table tipo_mensaje_boton add constraint FKtipo_mensa440195 foreign key (tipo_mensajeid) references tipo_mensaje (id);
alter table tipo_mensaje_boton add constraint FKtipo_mensa419544 foreign key (botonid) references boton (id);
alter table publicidad add constraint FKpublicidad730376 foreign key (imagenid) references imagen (id);
alter table difusion add constraint FKdifusion100202 foreign key (imagenid) references imagen (id);
alter table hospital_difusion add constraint FKhospital_d534175 foreign key (hospitalid) references hospital (id);
alter table hospital_difusion add constraint FKhospital_d84418 foreign key (difusionid) references difusion (id);
alter table boletin_informativo_publicacion add constraint FKboletin_in761868 foreign key (boletin_informativoid) references boletin_informativo (id);
alter table boletin_informativo_publicacion add constraint FKboletin_in615061 foreign key (publicacionid) references publicacion (id);
alter table suscripcion_tipo_publicacion add constraint FKsuscripcio94154 foreign key (suscripcionid) references suscripcion (id);
alter table suscripcion_tipo_publicacion add constraint FKsuscripcio593834 foreign key (tipo_publicacionid) references tipo_publicacion (id);
alter table usuario add constraint FKusuario60765 foreign key (cedula) references persona (cedula);
alter table recepcionista add constraint FKrecepcioni1824 foreign key (cedula) references persona (cedula);
alter table responsable add constraint FKresponsabl627805 foreign key (cedula) references persona (cedula);
alter table paciente add constraint FKpaciente205622 foreign key (responsablecedula) references responsable (cedula);
alter table publicacion add constraint FKpublicacio110160 foreign key (usuariocedula) references usuario (cedula);
alter table respuesta add constraint FKrespuesta195289 foreign key (usuariocedula) references usuario (cedula);
alter table historial add constraint FKhistorial19806 foreign key (pacientehistoria_medica) references paciente (historia_medica);
alter table defuncion add constraint FKdefuncion208093 foreign key (id) references historial (id);
alter table ficha_medica add constraint FKficha_medi620779 foreign key (id) references historial (id);
alter table consulta_general add constraint FKconsulta_g191672 foreign key (id) references historial (id);
alter table dermatologia add constraint FKdermatolog769416 foreign key (id) references historial (id);
alter table cardiologia add constraint FKcardiologi385162 foreign key (id) references historial (id);
alter table oftalmologia add constraint FKoftalmolog803580 foreign key (id) references historial (id);
alter table neurologia add constraint FKneurologia860390 foreign key (id) references historial (id);
alter table historial add constraint FKhistorial358592 foreign key (tipo_servicioid) references tipo_servicio (id);
alter table pre_operatorio add constraint FKpre_operat537317 foreign key (id) references historial (id);
alter table post_operatorio add constraint FKpost_opera30951 foreign key (id) references historial (id);
alter table historial_sintoma add constraint FKhistorial_651908 foreign key (historialid) references historial (id);
alter table historial_sintoma add constraint FKhistorial_779122 foreign key (sintomaid) references sintoma (id);
alter table tratamiento add constraint FKtratamient942680 foreign key (tipo_tratamientoid) references tipo_tratamiento (id);
alter table historial_tratamiento add constraint FKhistorial_725760 foreign key (historialid) references historial (id);
alter table historial_tratamiento add constraint FKhistorial_337316 foreign key (tratamientoid) references tratamiento (id);
alter table historial_patologia add constraint FKhistorial_123676 foreign key (historialid) references historial (id);
alter table historial_patologia add constraint FKhistorial_804440 foreign key (patologiaid) references patologia (id);
alter table carnet add constraint FKcarnet67037 foreign key (pacientehistoria_medica) references paciente (historia_medica);
alter table referencia add constraint FKreferencia900872 foreign key (historialid) references historial (id);
alter table patologia add constraint FKpatologia16393 foreign key (tipo_patologiaid) references tipo_patologia (id);
alter table defuncion add constraint FKdefuncion426524 foreign key (tipo_defuncionid) references tipo_defuncion (id);
alter table traumatologia add constraint FKtraumatolo247508 foreign key (id) references historial (id);
alter table laboratorio add constraint FKlaboratori343339 foreign key (id) references historial (id);
alter table imagenologia add constraint FKimagenolog721732 foreign key (id) references historial (id);
alter table cirugia add constraint FKcirugia991966 foreign key (id) references historial (id);
alter table historial add constraint FKhistorial98974 foreign key (veterinariocedula) references veterinario (cedula);
alter table referencia add constraint FKreferencia197182 foreign key (tipo_referenciaid) references tipo_referencia (id);
alter table entidad_externa add constraint FKentidad_ex237233 foreign key (imagenid) references imagen (id);
alter table hospital add constraint FKhospital506288 foreign key (imagenid) references imagen (id);
alter table dia_de_atencion add constraint FKdia_de_ate87547 foreign key (diaid) references dia (id);
alter table dia_de_atencion add constraint FKdia_de_ate355025 foreign key (tipo_servicioid) references tipo_servicio (id);
alter table usuario_perfil add constraint FKusuario_pe683015 foreign key (usuariocedula) references usuario (cedula);
alter table usuario_perfil add constraint FKusuario_pe314971 foreign key (perfilid) references perfil (id);
alter table perfil_funcion add constraint FKperfil_fun620910 foreign key (perfilid) references perfil (id);
alter table perfil_funcion add constraint FKperfil_fun77026 foreign key (funcionid) references funcion (id);
alter table funcion add constraint FKfuncion858319 foreign key (funcionid) references funcion (id);
alter table historial_servicio add constraint FKhistorial_440112 foreign key (historialid) references historial (id);
alter table historial_servicio add constraint FKhistorial_996219 foreign key (servicioid) references servicio (id);
alter table tipo_servicio_web add constraint FKtipo_servi653871 foreign key (tipo_servicioid) references tipo_servicio (id);
alter table respuesta add constraint FKrespuesta510836 foreign key (notificacionid) references notificacion (id);
alter table tipo_referencia_tipo_servicio add constraint FKtipo_refer9246 foreign key (tipo_referenciaid) references tipo_referencia (id);
alter table tipo_referencia_tipo_servicio add constraint FKtipo_refer709553 foreign key (tipo_servicioid) references tipo_servicio (id);
