package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BoletinInformativo generated by hbm2java
 */
@Entity
@Table(name = "boletin_informativo", schema = "public")
public class BoletinInformativo implements java.io.Serializable {

	private int id;
	private String titulo;
	private String texto;
	private Date creacion;
	private Date envio;
	private boolean enviado;
	private char estatus;
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public BoletinInformativo() {
	}

	public BoletinInformativo(int id, String titulo, Date creacion,
			boolean enviado, char estatus) {
		this.id = id;
		this.titulo = titulo;
		this.creacion = creacion;
		this.enviado = enviado;
		this.estatus = estatus;
	}

	public BoletinInformativo(int id, String titulo, String texto,
			Date creacion, Date envio, boolean enviado, char estatus,
			Set<Publicacion> publicacions) {
		this.id = id;
		this.titulo = titulo;
		this.texto = texto;
		this.creacion = creacion;
		this.envio = envio;
		this.enviado = enviado;
		this.estatus = estatus;
		this.publicacions = publicacions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "envio", length = 13)
	public Date getEnvio() {
		return this.envio;
	}

	public void setEnvio(Date envio) {
		this.envio = envio;
	}

	@Column(name = "enviado", nullable = false)
	public boolean isEnviado() {
		return this.enviado;
	}

	public void setEnviado(boolean enviado) {
		this.enviado = enviado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "boletin_informativo_publicacion", schema = "public", joinColumns = { @JoinColumn(name = "boletin_informativoid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "publicacionid", nullable = false, updatable = false) })
	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
