package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", schema = "public")
public class Ciudad implements java.io.Serializable {

	private int id;
	private Estado estado;
	private String nombre;
	private String codigoPostal;
	private char estatus;
	private Set<Hospital> hospitals = new HashSet<Hospital>(0);
	private Set<EntidadExterna> entidadExternas = new HashSet<EntidadExterna>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Ciudad() {
	}

	public Ciudad(int id, Estado estado, String nombre, char estatus) {
		this.id = id;
		this.estado = estado;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Ciudad(int id, Estado estado, String nombre, String codigoPostal,
			char estatus, Set<Hospital> hospitals,
			Set<EntidadExterna> entidadExternas, Set<Persona> personas) {
		this.id = id;
		this.estado = estado;
		this.nombre = nombre;
		this.codigoPostal = codigoPostal;
		this.estatus = estatus;
		this.hospitals = hospitals;
		this.entidadExternas = entidadExternas;
		this.personas = personas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estadoid", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_postal", length = 5)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Hospital> getHospitals() {
		return this.hospitals;
	}

	public void setHospitals(Set<Hospital> hospitals) {
		this.hospitals = hospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<EntidadExterna> getEntidadExternas() {
		return this.entidadExternas;
	}

	public void setEntidadExternas(Set<EntidadExterna> entidadExternas) {
		this.entidadExternas = entidadExternas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
