package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Difusion generated by hbm2java
 */
@Entity
@Table(name = "difusion", schema = "public")
public class Difusion implements java.io.Serializable {

	private int id;
	private Imagen imagen;
	private String nombre;
	private String enlace;
	private char estatus;
	private Set<HospitalDifusion> hospitalDifusions = new HashSet<HospitalDifusion>(
			0);

	public Difusion() {
	}

	public Difusion(int id, String nombre, String enlace, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.enlace = enlace;
		this.estatus = estatus;
	}

	public Difusion(int id, Imagen imagen, String nombre, String enlace,
			char estatus, Set<HospitalDifusion> hospitalDifusions) {
		this.id = id;
		this.imagen = imagen;
		this.nombre = nombre;
		this.enlace = enlace;
		this.estatus = estatus;
		this.hospitalDifusions = hospitalDifusions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imagenid")
	public Imagen getImagen() {
		return this.imagen;
	}

	public void setImagen(Imagen imagen) {
		this.imagen = imagen;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "enlace", nullable = false)
	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "difusion")
	public Set<HospitalDifusion> getHospitalDifusions() {
		return this.hospitalDifusions;
	}

	public void setHospitalDifusions(Set<HospitalDifusion> hospitalDifusions) {
		this.hospitalDifusions = hospitalDifusions;
	}

}
