package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name = "imagen", schema = "public")
public class Imagen implements java.io.Serializable {

	private int id;
	private String nombre;
	private byte[] bytes;
	private String extension;
	private Date creacion;
	private char estatus;
	private Set<Difusion> difusions = new HashSet<Difusion>(0);
	private Set<EntidadExterna> entidadExternas = new HashSet<EntidadExterna>(0);
	private Set<Publicidad> publicidads = new HashSet<Publicidad>(0);
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);
	private Set<Hospital> hospitals = new HashSet<Hospital>(0);

	public Imagen() {
	}

	public Imagen(int id, String nombre, byte[] bytes, String extension,
			Date creacion, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.bytes = bytes;
		this.extension = extension;
		this.creacion = creacion;
		this.estatus = estatus;
	}

	public Imagen(int id, String nombre, byte[] bytes, String extension,
			Date creacion, char estatus, Set<Difusion> difusions,
			Set<EntidadExterna> entidadExternas, Set<Publicidad> publicidads,
			Set<Publicacion> publicacions, Set<Hospital> hospitals) {
		this.id = id;
		this.nombre = nombre;
		this.bytes = bytes;
		this.extension = extension;
		this.creacion = creacion;
		this.estatus = estatus;
		this.difusions = difusions;
		this.entidadExternas = entidadExternas;
		this.publicidads = publicidads;
		this.publicacions = publicacions;
		this.hospitals = hospitals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "bytes", nullable = false)
	public byte[] getBytes() {
		return this.bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

	@Column(name = "extension", nullable = false, length = 5)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<Difusion> getDifusions() {
		return this.difusions;
	}

	public void setDifusions(Set<Difusion> difusions) {
		this.difusions = difusions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<EntidadExterna> getEntidadExternas() {
		return this.entidadExternas;
	}

	public void setEntidadExternas(Set<EntidadExterna> entidadExternas) {
		this.entidadExternas = entidadExternas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<Publicidad> getPublicidads() {
		return this.publicidads;
	}

	public void setPublicidads(Set<Publicidad> publicidads) {
		this.publicidads = publicidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<Hospital> getHospitals() {
		return this.hospitals;
	}

	public void setHospitals(Set<Hospital> hospitals) {
		this.hospitals = hospitals;
	}

}
