package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", schema = "public")
public class Paciente implements java.io.Serializable {

	private String historiaMedica;
	private Responsable responsable;
	private Sexo sexo;
	private Raza raza;
	private String nombre;
	private Date fechaNac;
	private Date creacion;
	private char estatus;
	private Set<Historial> historials = new HashSet<Historial>(0);
	private Set<Carnet> carnets = new HashSet<Carnet>(0);

	public Paciente() {
	}

	public Paciente(String historiaMedica, Responsable responsable, Sexo sexo,
			Raza raza, String nombre, Date fechaNac, Date creacion, char estatus) {
		this.historiaMedica = historiaMedica;
		this.responsable = responsable;
		this.sexo = sexo;
		this.raza = raza;
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.creacion = creacion;
		this.estatus = estatus;
	}

	public Paciente(String historiaMedica, Responsable responsable, Sexo sexo,
			Raza raza, String nombre, Date fechaNac, Date creacion,
			char estatus, Set<Historial> historials, Set<Carnet> carnets) {
		this.historiaMedica = historiaMedica;
		this.responsable = responsable;
		this.sexo = sexo;
		this.raza = raza;
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.creacion = creacion;
		this.estatus = estatus;
		this.historials = historials;
		this.carnets = carnets;
	}

	@Id
	@Column(name = "historia_medica", unique = true, nullable = false, length = 20)
	public String getHistoriaMedica() {
		return this.historiaMedica;
	}

	public void setHistoriaMedica(String historiaMedica) {
		this.historiaMedica = historiaMedica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsablecedula", nullable = false)
	public Responsable getResponsable() {
		return this.responsable;
	}

	public void setResponsable(Responsable responsable) {
		this.responsable = responsable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sexoid", nullable = false)
	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "razaid", nullable = false)
	public Raza getRaza() {
		return this.raza;
	}

	public void setRaza(Raza raza) {
		this.raza = raza;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", nullable = false, length = 13)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set<Historial> historials) {
		this.historials = historials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Carnet> getCarnets() {
		return this.carnets;
	}

	public void setCarnets(Set<Carnet> carnets) {
		this.carnets = carnets;
	}

}
