package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private char estatus;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Funcion> funcions = new HashSet<Funcion>(0);

	public Perfil() {
	}

	public Perfil(int id, String nombre, String descripcion, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public Perfil(int id, String nombre, String descripcion, char estatus,
			Set<Usuario> usuarios, Set<Funcion> funcions) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.usuarios = usuarios;
		this.funcions = funcions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_perfil", schema = "public", joinColumns = { @JoinColumn(name = "perfilid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "usuariocedula", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "perfil_funcion", schema = "public", joinColumns = { @JoinColumn(name = "perfilid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "funcionid", nullable = false, updatable = false) })
	public Set<Funcion> getFuncions() {
		return this.funcions;
	}

	public void setFuncions(Set<Funcion> funcions) {
		this.funcions = funcions;
	}

}
