package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicidad generated by hbm2java
 */
@Entity
@Table(name = "publicidad", schema = "public")
public class Publicidad implements java.io.Serializable {

	private int id;
	private Imagen imagen;
	private String titulo;
	private String descripcion;
	private Date creacion;
	private Date expiracion;
	private Integer clicks;
	private String enlace;
	private boolean activo;
	private char estatus;

	public Publicidad() {
	}

	public Publicidad(int id, String titulo, Date creacion, boolean activo,
			char estatus) {
		this.id = id;
		this.titulo = titulo;
		this.creacion = creacion;
		this.activo = activo;
		this.estatus = estatus;
	}

	public Publicidad(int id, Imagen imagen, String titulo, String descripcion,
			Date creacion, Date expiracion, Integer clicks, String enlace,
			boolean activo, char estatus) {
		this.id = id;
		this.imagen = imagen;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.creacion = creacion;
		this.expiracion = expiracion;
		this.clicks = clicks;
		this.enlace = enlace;
		this.activo = activo;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imagenid")
	public Imagen getImagen() {
		return this.imagen;
	}

	public void setImagen(Imagen imagen) {
		this.imagen = imagen;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiracion", length = 13)
	public Date getExpiracion() {
		return this.expiracion;
	}

	public void setExpiracion(Date expiracion) {
		this.expiracion = expiracion;
	}

	@Column(name = "clicks")
	public Integer getClicks() {
		return this.clicks;
	}

	public void setClicks(Integer clicks) {
		this.clicks = clicks;
	}

	@Column(name = "enlace")
	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
