package org.ucla.sigma.modelo;

// Generated 15/07/2012 02:32:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServicio generated by hbm2java
 */
@Entity
@Table(name = "tipo_servicio", schema = "public")
public class TipoServicio implements java.io.Serializable {

	private String id;
	private String nombre;
	private String vista;
	private char estatus;
	private Set<TipoServicioWeb> tipoServicioWebs = new HashSet<TipoServicioWeb>(
			0);
	private Set<Referencia> referencias = new HashSet<Referencia>(0);
	private Set<DiaDeAtencion> diaDeAtencions = new HashSet<DiaDeAtencion>(0);
	private Set<Historial> historials = new HashSet<Historial>(0);
	private Set<Servicio> servicios = new HashSet<Servicio>(0);
	private Set<TipoReferencia> tipoReferencias = new HashSet<TipoReferencia>(0);

	public TipoServicio() {
	}

	public TipoServicio(String id, String nombre, String vista, char estatus) {
		this.id = id;
		this.nombre = nombre;
		this.vista = vista;
		this.estatus = estatus;
	}

	public TipoServicio(String id, String nombre, String vista, char estatus,
			Set<TipoServicioWeb> tipoServicioWebs, Set<Referencia> referencias,
			Set<DiaDeAtencion> diaDeAtencions, Set<Historial> historials,
			Set<Servicio> servicios, Set<TipoReferencia> tipoReferencias) {
		this.id = id;
		this.nombre = nombre;
		this.vista = vista;
		this.estatus = estatus;
		this.tipoServicioWebs = tipoServicioWebs;
		this.referencias = referencias;
		this.diaDeAtencions = diaDeAtencions;
		this.historials = historials;
		this.servicios = servicios;
		this.tipoReferencias = tipoReferencias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 5)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "vista", nullable = false)
	public String getVista() {
		return this.vista;
	}

	public void setVista(String vista) {
		this.vista = vista;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<TipoServicioWeb> getTipoServicioWebs() {
		return this.tipoServicioWebs;
	}

	public void setTipoServicioWebs(Set<TipoServicioWeb> tipoServicioWebs) {
		this.tipoServicioWebs = tipoServicioWebs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<Referencia> getReferencias() {
		return this.referencias;
	}

	public void setReferencias(Set<Referencia> referencias) {
		this.referencias = referencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<DiaDeAtencion> getDiaDeAtencions() {
		return this.diaDeAtencions;
	}

	public void setDiaDeAtencions(Set<DiaDeAtencion> diaDeAtencions) {
		this.diaDeAtencions = diaDeAtencions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<Historial> getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set<Historial> historials) {
		this.historials = historials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio> servicios) {
		this.servicios = servicios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tipo_referencia_tipo_servicio", schema = "public", joinColumns = { @JoinColumn(name = "tipo_servicioid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "tipo_referenciaid", nullable = false, updatable = false) })
	public Set<TipoReferencia> getTipoReferencias() {
		return this.tipoReferencias;
	}

	public void setTipoReferencias(Set<TipoReferencia> tipoReferencias) {
		this.tipoReferencias = tipoReferencias;
	}

}
